# Generated by Django 2.0.1 on 2018-01-30 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Literal',
            fields=[
                ('id_literal', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha_iniciacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Literal',
                'verbose_name_plural': 'Literales',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proyecto', models.CharField(max_length=15)),
                ('fecha_prometida', models.DateField(blank=True, null=True)),
                ('cerrado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.AddField(
            model_name='literal',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_literales', to='proyectos.Proyecto'),
        ),
    ]
