# Generated by Django 2.0.1 on 2018-01-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_literal_costo_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='literal',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
