# Generated by Django 2.0.1 on 2018-01-30 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_auto_20180130_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='literal',
            name='fecha_iniciacion',
        ),
    ]
