# Generated by Django 2.0.1 on 2018-01-30 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_auto_20180130_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literal',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_literales', to='proyectos.Proyecto'),
        ),
    ]
