# Generated by Django 2.0.1 on 2018-01-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_remove_literal_fecha_iniciacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='literal',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='literal',
            name='id_literal',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
