# Generated by Django 2.0.1 on 2018-01-30 18:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0009_auto_20180130_1733'),
        ('proyectos', '0004_auto_20180130_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraColaboradorLiteralProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('minutos', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cguno.ColaboradorBiable')),
                ('literal_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyectos.Literal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='literal',
            name='horas_colaboradores',
            field=models.ManyToManyField(through='proyectos.HoraColaboradorLiteralProyecto', to='cguno.ColaboradorBiable'),
        ),
    ]
