# Generated by Django 2.0.1 on 2018-02-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_auto_20180130_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='literal',
            old_name='costo_total',
            new_name='costo_materiales',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='costo_total',
            new_name='costo_materiales',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='cerrado',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='abierto',
            field=models.BooleanField(default=True),
        ),
    ]
