# Generated by Django 2.0.1 on 2018-02-02 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_auto_20180202_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': [('list_proyecto', 'Can see list proyectos'), ('detail_proyecto', 'Can see detail proyecto')], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
    ]
