# Generated by Django 2.0.1 on 2018-02-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_auto_20180202_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': [('list_proyecto', 'Can see list proyectos'), ('detail_proyecto', 'Can see detail proyecto'), ('valor_proyecto', 'Ver valor proyecto'), ('costo_proyecto', 'Ver costo proyecto'), ('costo_presupuestado_proyecto', 'Ver costo presupuestado proyecto')], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AddField(
            model_name='proyecto',
            name='costo_presupuestado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='valor_cliente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
