# Generated by Django 2.0.1 on 2018-02-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0009_auto_20180205_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='literal',
            name='costo_mano_obra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
