# Generated by Django 2.0.1 on 2018-02-07 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0011_proyecto_costo_mano_obra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horacolaboradorliteralproyecto',
            name='colaborador',
        ),
        migrations.RemoveField(
            model_name='horacolaboradorliteralproyecto',
            name='literal_proyecto',
        ),
        migrations.RemoveField(
            model_name='literal',
            name='horas_colaboradores',
        ),
        migrations.DeleteModel(
            name='HoraColaboradorLiteralProyecto',
        ),
    ]
