# Generated by Django 2.0.1 on 2018-02-07 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0012_auto_20180207_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='literal',
            name='costo_mano_obra',
        ),
    ]
