# Generated by Django 2.0.1 on 2018-02-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0013_remove_literal_costo_mano_obra'),
    ]

    operations = [
        migrations.AddField(
            model_name='literal',
            name='costo_mano_obra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
