# Generated by Django 2.0.1 on 2018-02-20 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0017_auto_20180207_0452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': [('list_proyecto', 'Can see list proyectos'), ('detail_proyecto', 'Can see detail proyecto'), ('valor_proyecto', 'Ver valor proyecto'), ('costo_proyecto', 'Ver costo proyecto'), ('costo_mano_obra_proyecto', 'Ver costo MO proyecto'), ('costo_materiales_proyecto', 'Ver costo materiales proyecto'), ('costo_presupuestado_proyecto', 'Ver costo presupuestado proyecto')], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
    ]
