# Generated by Django 2.0.1 on 2018-03-16 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0019_auto_20180226_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='costo_mano_obra',
        ),
    ]
