# Generated by Django 2.0.1 on 2018-03-16 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0020_remove_proyecto_costo_mano_obra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='literal',
            name='costo_mano_obra',
        ),
    ]
