# Generated by Django 2.0.4 on 2018-04-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0021_remove_literal_costo_mano_obra'),
    ]

    operations = [
        migrations.AddField(
            model_name='literal',
            name='fecha_entrega_pactada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='literal',
            name='orden_compra_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='literal',
            name='orden_compra_nro',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='literal',
            name='valor_cliente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_entrega_pactada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='orden_compra_fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
