# Generated by Django 2.0.4 on 2018-04-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0023_literal_en_cguno'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='en_cguno',
            field=models.BooleanField(default=True),
        ),
    ]
