# Generated by Django 2.0.4 on 2018-04-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0026_literal_abierto'),
    ]

    operations = [
        migrations.AddField(
            model_name='literal',
            name='cotizacion_nro',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='cotizacion_nro',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
