# Generated by Django 2.0.4 on 2018-04-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0027_auto_20180425_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='literal',
            options={},
        ),
        migrations.AddField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
