# Generated by Django 2.0.4 on 2018-05-15 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0013_cotizacion_abrir_carpeta'),
        ('proyectos', '0029_proyecto_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mi_proyecto', to='cotizaciones.Cotizacion'),
        ),
    ]
