# Generated by Django 2.0.4 on 2018-05-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0030_proyecto_proyecto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='proyecto',
            new_name='cotizacion',
        ),
    ]
