# Generated by Django 2.0.4 on 2018-05-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0031_auto_20180515_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='cotizacion_nro',
        ),
    ]
