# Generated by Django 2.0.4 on 2018-05-15 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0032_remove_proyecto_cotizacion_nro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='costo_presupuestado',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='valor_cliente',
        ),
    ]
