# Generated by Django 2.0.4 on 2018-05-15 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0033_auto_20180515_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='cotizacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mi_proyecto', to='cotizaciones.Cotizacion'),
        ),
    ]
