# Generated by Django 2.0.4 on 2018-05-31 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0036_auto_20180531_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='literal',
            name='fecha_entrega_pactada',
        ),
        migrations.RemoveField(
            model_name='literal',
            name='orden_compra_fecha',
        ),
        migrations.RemoveField(
            model_name='literal',
            name='orden_compra_nro',
        ),
        migrations.RemoveField(
            model_name='literal',
            name='valor_cliente',
        ),
    ]
