# Generated by Django 2.0.4 on 2018-05-31 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0037_auto_20180531_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='literal',
            name='cotizacion_nro',
        ),
    ]
