# Generated by Django 2.0.4 on 2018-06-12 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0039_auto_20180607_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literal',
            name='cotizacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mi_literal', to='cotizaciones.Cotizacion'),
        ),
    ]
