# Generated by Django 2.0.4 on 2018-09-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0041_auto_20180926_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miembroliteral',
            old_name='puede_editar',
            new_name='puede_adicionar_tareas',
        ),
        migrations.RenameField(
            model_name='miembroliteral',
            old_name='puede_eliminar',
            new_name='puede_administrar_fases',
        ),
        migrations.AddField(
            model_name='miembroliteral',
            name='puede_administrar_miembros',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='miembroliteral',
            name='puede_editar_tareas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='miembroliteral',
            name='puede_eliminar_tareas',
            field=models.BooleanField(default=False),
        ),
    ]
