# Generated by Django 2.0.4 on 2018-10-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0042_auto_20180926_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miembroliteral',
            name='puede_ver',
        ),
    ]
