# Generated by Django 2.1.4 on 2018-12-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0045_auto_20181227_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literal',
            name='abierto',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='abierto',
            field=models.BooleanField(default=True),
        ),
    ]
