# Generated by Django 2.0.4 on 2019-01-22 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import proyectos.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0046_auto_20181227_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoLiteral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre_archivo', models.CharField(max_length=300)),
                ('archivo', models.FileField(null=True, upload_to=proyectos.models.ArchivoLiteral.archivo_upload_to)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('literal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_documentos', to='proyectos.Literal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArchivoProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre_archivo', models.CharField(max_length=300)),
                ('archivo', models.FileField(null=True, upload_to=proyectos.models.ArchivoProyecto.archivo_upload_to)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_documentos', to='proyectos.Proyecto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
