# Generated by Django 2.0.4 on 2019-01-23 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0047_archivoliteral_archivoproyecto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivoliteral',
            options={'permissions': [('list_archivoliteral', 'Can see list archivos literales')]},
        ),
        migrations.AlterModelOptions(
            name='archivoproyecto',
            options={'permissions': [('list_archivoproyecto', 'Can see list archivos proyectos')]},
        ),
    ]
