# Generated by Django 2.2 on 2019-07-03 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0048_auto_20190123_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaLiteral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('documento', models.CharField(max_length=15)),
                ('concepto', models.CharField(max_length=300)),
                ('valor_sin_impuesto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('literal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='proyectos.Literal')),
            ],
        ),
    ]
