# Generated by Django 2.2 on 2019-07-04 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0049_facturaliteral'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facturaliteral',
            unique_together={('literal', 'concepto', 'documento', 'fecha')},
        ),
    ]
