# Generated by Django 2.2.6 on 2019-10-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0042_auto_20191019_0954'),
        ('proyectos', '0053_auto_20191019_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='literal',
            name='cotizaciones',
            field=models.ManyToManyField(related_name='literales', to='cotizaciones.Cotizacion'),
        ),
    ]
