# Generated by Django 2.2.6 on 2019-11-12 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0055_auto_20191105_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='literal',
            name='disenador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disenos_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
