# Generated by Django 2.2.6 on 2019-11-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0056_literal_disenador'),
    ]

    operations = [
        migrations.AddField(
            model_name='literal',
            name='correo_apertura',
            field=models.BooleanField(default=True),
        ),
    ]
