# Generated by Django 2.2.6 on 2019-11-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0057_literal_correo_apertura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literal',
            name='correo_apertura',
            field=models.BooleanField(default=False),
        ),
    ]
