# Generated by Django 2.2.6 on 2019-12-17 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0058_auto_20191129_0810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': [('list_consecutivo_proyectos', 'Can list consecutivo proyectos'), ('enviar_soliciud_apertura_proyectos_al_almacen_proyectos', 'Enviar Solicitud Apertura Proyectos al Almacen'), ('list_proyecto', 'Can see list proyectos'), ('detail_proyecto', 'Can see detail proyecto'), ('valor_proyecto', 'Ver valor proyecto'), ('costo_proyecto', 'Ver costo proyecto'), ('costo_mano_obra_proyecto', 'Ver costo MO proyecto'), ('costo_materiales_proyecto', 'Ver costo materiales proyecto'), ('costo_presupuestado_proyecto', 'Ver costo presupuestado proyecto'), ('admon_proyecto_project_manager', 'Administrador Project Manager'), ('detail_proyecto_project_manager', 'Ver Project Manager')]},
        ),
    ]
