# Generated by Django 2.2.6 on 2019-12-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0060_auto_20191218_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='cotizacion_componentes_nro_orden_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
