# Generated by Django 2.2.6 on 2019-12-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0061_proyecto_cotizacion_componentes_nro_orden_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='cotizacion_componentes_nro_orden_compra',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
