# Generated by Django 2.2.6 on 2019-12-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0062_auto_20191218_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='cotizacion_componentes_nro_cotizacion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='cotizacion_componentes_nro_orden_compra',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
