# Generated by Django 2.2.6 on 2020-02-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0064_auto_20200211_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literal',
            name='id_literal',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='id_proyecto',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
    ]
