# Generated by Django 2.2.6 on 2020-01-30 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_catalogos', '0029_auto_20200130_1108'),
        ('colaboradores', '0002_auto_20200130_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cargues_catalogos.CargoColaboradorCatalogo'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='centro_costo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='costos_mensuales_colaboradores', to='cargues_catalogos.ColaboradorCentroCostoCatalogo'),
        ),
    ]
