# Generated by Django 2.2.6 on 2020-02-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0003_auto_20200130_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='alias_correo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='nro_contacto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
