# Generated by Django 2.2 on 2019-06-11 12:17

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import sistemas_equipos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoCelular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.IntegerField(choices=[(1, 'SAMSUNG'), (2, 'HUAWEY'), (3, 'HONOR')])),
                ('referencia', models.CharField(max_length=50)),
                ('imei_1', models.CharField(max_length=30)),
                ('imei_2', models.CharField(max_length=30, null=True)),
                ('numero_1', models.CharField(max_length=20)),
                ('numero_2', models.CharField(max_length=20, null=True)),
                ('descripcion', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipoComputador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('marca', models.IntegerField(choices=[(1, 'SONY'), (2, 'TOSHIBA'), (3, 'LENOVO'), (4, 'ASUS'), (5, 'DELL'), (6, 'MAC')])),
                ('referencia', models.CharField(max_length=50, null=True)),
                ('procesador', models.IntegerField(choices=[(1, 'CORE I3'), (2, 'CORE I5'), (3, 'CORE I7'), (4, 'AMD')])),
                ('tipo', models.IntegerField(choices=[(1, 'ESCRITORIO'), (2, 'PORTATIL')])),
                ('serial', models.CharField(max_length=50, null=True)),
                ('estado', models.IntegerField(choices=[(1, 'EN PRODUCCIÓN'), (2, 'FUERA DE PRODUCCIÓN')], default=1)),
                ('descripcion', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipoComputadorFoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, null=True)),
                ('foto', imagekit.models.fields.ProcessedImageField(null=True, upload_to=sistemas_equipos.models.EquipoComputadorFoto.archivo_upload_to)),
                ('computador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistemas_equipos.EquipoComputador')),
            ],
        ),
        migrations.CreateModel(
            name='EquipoCelularFoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, null=True)),
                ('foto', imagekit.models.fields.ProcessedImageField(null=True, upload_to=sistemas_equipos.models.EquipoCelularFoto.archivo_upload_to)),
                ('celular', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistemas_equipos.EquipoCelular')),
            ],
        ),
    ]
