# Generated by Django 2.2 on 2019-06-11 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas_equipos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipocomputador',
            options={'permissions': [('list_sequipocomputador', 'Can list computadores')]},
        ),
    ]
