# Generated by Django 2.2 on 2019-06-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas_equipos', '0002_auto_20190611_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipocomputador',
            name='marca',
            field=models.IntegerField(choices=[(1, 'SONY'), (2, 'TOSHIBA'), (3, 'LENOVO'), (4, 'ASUS'), (5, 'DELL'), (6, 'MAC'), (7, 'HP'), (8, 'INTEL'), (9, 'MICROSOFT'), (10, 'SIEMMENS'), (11, 'INTEL')]),
        ),
        migrations.AlterField(
            model_name='equipocomputador',
            name='procesador',
            field=models.IntegerField(choices=[(1, 'CORE I3'), (2, 'CORE I5'), (3, 'CORE I7'), (4, 'AMD E1'), (5, 'CENTRINO'), (6, 'PENTIUM'), (7, 'XEON'), (8, 'CORE 2 DUO'), (9, 'CELERON'), (10, 'CORE 2')]),
        ),
    ]
