# Generated by Django 5.0.14 on 2026-01-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas_equipos', '0003_auto_20190612_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipocelular',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='equipocelularfoto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='equipocomputador',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='equipocomputadorfoto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
