# Generated by Django 2.0.1 on 2018-01-29 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0002_auto_20180129_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemsbiable',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
    ]
