# Generated by Django 2.0.1 on 2018-01-30 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_auto_20180130_1412'),
        ('cguno', '0003_auto_20180129_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsLiteralBiable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_biable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cguno.ItemsBiable')),
                ('literal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyectos.Literal', verbose_name='mis_items_biable')),
            ],
            options={
                'verbose_name': 'Item Literales Proyecto',
                'verbose_name_plural': 'Items Literales Proyecto',
            },
        ),
    ]
