# Generated by Django 2.0.1 on 2018-01-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0005_auto_20180130_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsliteralbiable',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
