# Generated by Django 2.0.1 on 2018-01-30 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0008_colaboradorbiable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradorbiable',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='colaborador', to=settings.AUTH_USER_MODEL),
        ),
    ]
