# Generated by Django 2.0.1 on 2018-02-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0009_auto_20180130_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradorbiable',
            name='autogestion_horas_trabajadas',
            field=models.BooleanField(default=False),
        ),
    ]
