# Generated by Django 2.0.1 on 2018-02-09 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0010_colaboradorbiable_autogestion_horas_trabajadas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemsbiable',
            options={'permissions': [('list_itemsbiable', 'Can see list items CGUNO')], 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
    ]
