# Generated by Django 2.0.1 on 2018-02-09 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0011_auto_20180209_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemsbiable',
            options={'permissions': [('list_itemsbiable', 'Can see list items CGUNO'), ('ultimo_costo_itemsbiable', 'Can see ultimo costo items CGUNO')], 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
    ]
