# Generated by Django 2.0.1 on 2018-02-12 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0013_auto_20180212_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradorbiable',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaborador', to=settings.AUTH_USER_MODEL),
        ),
    ]
