# Generated by Django 2.0.1 on 2018-02-26 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0014_auto_20180212_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargosBiable',
            fields=[
                ('id_cargo', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('tipo_cargo', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='colaboradorbiable',
            name='salario_fijo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='colaboradorbiable',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cguno.CargosBiable'),
        ),
    ]
