# Generated by Django 2.0.1 on 2018-02-26 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0015_auto_20180226_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaboradorbiable',
            old_name='salario_fijo',
            new_name='es_salario_fijo',
        ),
    ]
