# Generated by Django 2.0.1 on 2018-02-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0018_auto_20180226_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradorbiable',
            name='salario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
