# Generated by Django 2.0.1 on 2018-02-28 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0019_colaboradorbiable_salario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaboradorbiable',
            old_name='salario',
            new_name='pagado_mes_anterior',
        ),
    ]
