# Generated by Django 2.0.1 on 2018-03-01 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0020_auto_20180228_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaboradorbiable',
            name='pagado_mes_anterior',
        ),
    ]
