# Generated by Django 2.0.1 on 2018-03-01 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0021_remove_colaboradorbiable_pagado_mes_anterior'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColaboradorCentroCosto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ColaboradorCostoMesBiable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lapso', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_costos', to='cguno.ColaboradorBiable')),
            ],
        ),
        migrations.AddField(
            model_name='colaboradorbiable',
            name='centro_costo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mis_colaboradores', to='cguno.ColaboradorCentroCosto'),
        ),
    ]
