# Generated by Django 2.0.1 on 2018-03-01 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0022_auto_20180301_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaboradorbiable',
            options={'permissions': [('list_colaboradorbiable', 'Can see list colaboradores CGUNO'), ('detail_colaboradorbiable', 'Can see detail colaborador CGUNO')], 'verbose_name': 'Colaborador', 'verbose_name_plural': 'Colaboradores'},
        ),
        migrations.AlterModelOptions(
            name='colaboradorcentrocosto',
            options={'permissions': [('list_colaboradorcentrocosto', 'Can see list centros costos colaboradores')]},
        ),
        migrations.AlterModelOptions(
            name='colaboradorcostomesbiable',
            options={'permissions': [('list_colaboradorcostomesbiable', 'Can see list colaborador costo mes')]},
        ),
    ]
