# Generated by Django 2.0.1 on 2018-03-01 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0023_auto_20180301_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaboradorcostomesbiable',
            options={'permissions': [('list_colaboradorcostomesbiable', 'Can see list colaborador costo mes'), ('detail_colaboradorcentrocosto', 'Can see detail colaborador')]},
        ),
    ]
