# Generated by Django 2.0.1 on 2018-03-01 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0024_auto_20180301_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaboradorcostomesbiable',
            options={'permissions': [('list_colaboradorcostomesbiable', 'Can see list colaborador costo mes')]},
        ),
    ]
