# Generated by Django 2.0.1 on 2018-03-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0025_auto_20180301_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradorcostomesbiable',
            name='lapso',
            field=models.DateField(unique=True),
        ),
    ]
