# Generated by Django 2.0.1 on 2018-03-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0028_auto_20180302_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaboradorbiable',
            name='paga_caja_compensacion',
        ),
        migrations.RemoveField(
            model_name='colaboradorbiable',
            name='paga_pension',
        ),
        migrations.AddField(
            model_name='colaboradorbiable',
            name='porcentaje_arl',
            field=models.DecimalField(decimal_places=4, default=2.436, max_digits=10),
        ),
        migrations.AddField(
            model_name='colaboradorbiable',
            name='porcentaje_caja_compensacion',
            field=models.DecimalField(decimal_places=4, default=4.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='colaboradorbiable',
            name='porcentaje_pension',
            field=models.DecimalField(decimal_places=4, default=12, max_digits=10),
        ),
    ]
