# Generated by Django 2.0.1 on 2018-03-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0029_auto_20180302_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaboradorcostomesbiable',
            old_name='valor',
            new_name='costo',
        ),
        migrations.AddField(
            model_name='colaboradorcostomesbiable',
            name='es_salario_fijo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='colaboradorcostomesbiable',
            name='nro_horas_mes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='colaboradorcostomesbiable',
            name='valor_hora',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
