# Generated by Django 2.0.1 on 2018-03-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0030_auto_20180313_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradorcostomesbiable',
            name='modificado',
            field=models.BooleanField(default=False),
        ),
    ]
