# Generated by Django 2.0.1 on 2018-03-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0031_colaboradorcostomesbiable_modificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradorcostomesbiable',
            name='porcentaje_arl',
            field=models.DecimalField(decimal_places=4, default=2.436, max_digits=10),
        ),
        migrations.AddField(
            model_name='colaboradorcostomesbiable',
            name='porcentaje_caja_compensacion',
            field=models.DecimalField(decimal_places=4, default=4.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='colaboradorcostomesbiable',
            name='porcentaje_pension',
            field=models.DecimalField(decimal_places=4, default=12, max_digits=10),
        ),
    ]
