# Generated by Django 2.0.1 on 2018-03-13 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0032_auto_20180313_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaboradorcostomesbiable',
            name='porcentaje_arl',
        ),
        migrations.RemoveField(
            model_name='colaboradorcostomesbiable',
            name='porcentaje_caja_compensacion',
        ),
        migrations.RemoveField(
            model_name='colaboradorcostomesbiable',
            name='porcentaje_pension',
        ),
    ]
