# Generated by Django 2.0.1 on 2018-03-13 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0033_auto_20180313_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaboradorcostomesbiable',
            name='valor_hora',
        ),
    ]
