# Generated by Django 2.0.1 on 2018-03-13 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0034_remove_colaboradorcostomesbiable_valor_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradorcostomesbiable',
            name='centro_costo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mis_coloaboradores_costos_mensuales', to='cguno.ColaboradorCentroCosto'),
        ),
    ]
