# Generated by Django 2.0.1 on 2018-04-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0036_colaboradorbiable_literales_autorizados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradorcentrocosto',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
