# Generated by Django 2.0.1 on 2018-04-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0038_colaboradorcentrocosto_centro_costo_padre'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradorcostomesbiable',
            name='auxilio_transporte',
            field=models.DecimalField(decimal_places=4, default=12, max_digits=10),
        ),
        migrations.AddField(
            model_name='colaboradorcostomesbiable',
            name='base_salario',
            field=models.DecimalField(decimal_places=4, default=12, max_digits=10),
        ),
    ]
