# Generated by Django 2.0.1 on 2018-04-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0039_auto_20180404_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradorcostomesbiable',
            name='base_salario',
            field=models.DecimalField(decimal_places=4, default=12, max_digits=20),
        ),
        migrations.AlterField(
            model_name='colaboradorcostomesbiable',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
