# Generated by Django 2.0.1 on 2018-04-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0040_auto_20180404_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradorcostomesbiable',
            name='auxilio_transporte',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='colaboradorcostomesbiable',
            name='base_salario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
