# Generated by Django 2.0.1 on 2018-04-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0041_auto_20180404_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradorcostomesbiable',
            name='nro_horas_mes_trabajadas',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
