# Generated by Django 2.0.1 on 2018-04-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0043_auto_20180404_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradorbiable',
            name='porcentaje_salud',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
