# Generated by Django 2.0.1 on 2018-04-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0044_auto_20180404_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradorcostomesbiable',
            name='es_aprendiz_sena',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='colaboradorcostomesbiable',
            name='porcentaje_arl',
            field=models.DecimalField(decimal_places=4, default=2.436, max_digits=10),
        ),
        migrations.AddField(
            model_name='colaboradorcostomesbiable',
            name='porcentaje_caja_compensacion',
            field=models.DecimalField(decimal_places=4, default=4.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='colaboradorcostomesbiable',
            name='porcentaje_pension',
            field=models.DecimalField(decimal_places=4, default=12, max_digits=10),
        ),
        migrations.AddField(
            model_name='colaboradorcostomesbiable',
            name='porcentaje_salud',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
