# Generated by Django 2.0.1 on 2018-04-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0045_auto_20180404_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradorbiable',
            name='base_salario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='colaboradorbiable',
            name='porcentaje_prestaciones_sociales',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='colaboradorcostomesbiable',
            name='porcentaje_prestaciones_sociales',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
