# Generated by Django 2.0.1 on 2018-04-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0046_auto_20180404_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradorcostomesbiable',
            name='porcentaje_arl',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='colaboradorcostomesbiable',
            name='porcentaje_caja_compensacion',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='colaboradorcostomesbiable',
            name='porcentaje_pension',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
