# Generated by Django 2.0.1 on 2018-04-04 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0047_auto_20180404_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaboradorcostomesbiable',
            old_name='es_aprendiz_sena',
            new_name='es_aprendiz',
        ),
    ]
