# Generated by Django 2.0.1 on 2018-04-04 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0048_auto_20180404_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaboradorbiable',
            old_name='es_aprendiz_sena',
            new_name='es_aprendiz',
        ),
    ]
