# Generated by Django 2.0.1 on 2018-04-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0049_auto_20180404_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradorbiable',
            name='porcentaje_arl',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='colaboradorbiable',
            name='porcentaje_caja_compensacion',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='colaboradorbiable',
            name='porcentaje_pension',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
