# Generated by Django 2.0.1 on 2018-04-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0051_colaboradorbiable_auxilio_transporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradorcostomesbiable',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
    ]
