# Generated by Django 2.0.1 on 2018-04-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0052_colaboradorcostomesbiable_verificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradorcostomesbiable',
            name='autogestion_horas_trabajadas',
            field=models.BooleanField(default=False),
        ),
    ]
