# Generated by Django 2.0.1 on 2018-04-10 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0053_colaboradorcostomesbiable_autogestion_horas_trabajadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsliteralbiable',
            name='lapso',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
