# Generated by Django 2.0.1 on 2018-04-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0021_remove_literal_costo_mano_obra'),
        ('cguno', '0054_itemsliteralbiable_lapso'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemsliteralbiable',
            unique_together={('item_biable', 'literal', 'lapso')},
        ),
    ]
