# Generated by Django 2.0.1 on 2018-04-10 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0056_auto_20180410_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsliteralbiable',
            name='literal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_materiales', to='proyectos.Literal', verbose_name='mis_items_biable'),
        ),
    ]
