# Generated by Django 2.0.4 on 2018-06-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0058_colaboradorbiable_otro_costo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaboradorbiable',
            name='otro_costo',
        ),
        migrations.AddField(
            model_name='colaboradorcostomesbiable',
            name='otro_costo',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
