# Generated by Django 2.0.4 on 2018-06-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0059_auto_20180612_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradorcostomesbiable',
            name='otro_costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
