# Generated by Django 2.2 on 2019-06-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0060_auto_20180612_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradorcostomesbiable',
            name='nro_horas_mes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='colaboradorcostomesbiable',
            name='nro_horas_mes_trabajadas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
