# Generated by Django 2.2.6 on 2020-01-27 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0061_auto_20190612_1512'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemsLiteralBiable',
        ),
    ]
