# Generated by Django 2.2.6 on 2020-01-30 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0062_delete_itemsliteralbiable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemsbiable',
            options={},
        ),
        migrations.RemoveField(
            model_name='itemsbiable',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='itemsbiable',
            name='desc_item_padre',
        ),
        migrations.RemoveField(
            model_name='itemsbiable',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='itemsbiable',
            name='descripcion_dos',
        ),
        migrations.RemoveField(
            model_name='itemsbiable',
            name='id_procedencia',
        ),
        migrations.RemoveField(
            model_name='itemsbiable',
            name='nombre_tercero',
        ),
        migrations.RemoveField(
            model_name='itemsbiable',
            name='ultimo_costo',
        ),
        migrations.RemoveField(
            model_name='itemsbiable',
            name='unidad_medida_inventario',
        ),
    ]
