# Generated by Django 2.2.6 on 2020-01-30 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0063_auto_20200130_0850'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemsBiable',
            new_name='ItemsBiableS',
        ),
    ]
