# Generated by Django 2.2.6 on 2020-01-30 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0064_auto_20200130_0850'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemsBiableS',
        ),
    ]
