# Generated by Django 2.2.6 on 2020-09-03 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
import model_utils.fields
import postventa.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos_equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostventaRutinaTipoEquipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(db_column='desc')),
                ('mes', models.PositiveIntegerField()),
                ('tipo_equipo', models.ForeignKey(db_column='tip_equ', on_delete=django.db.models.deletion.PROTECT, related_name='rutinas_postventa', to='proyectos_equipos.TipoEquipo')),
            ],
            options={
                'db_table': 'postv_ruti_tip_equi',
                'permissions': [('list_postventarutinatipoequipo', 'Can list posventa rutinas tipo equipo')],
            },
        ),
        migrations.CreateModel(
            name='PostventaGarantia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fecha_inicial', models.DateField(db_column='fec_ini')),
                ('fecha_final', models.DateField(db_column='fec_fin')),
                ('creado_por', models.ForeignKey(blank=True, db_column='crt_by', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(db_column='equ', on_delete=django.db.models.deletion.PROTECT, related_name='garantias', to='proyectos_equipos.EquipoProyecto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostventaEventoEquipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(db_column='nombre', max_length=120)),
                ('archivo', models.FileField(db_column='file', null=True, upload_to=postventa.models.postventa_evento_equipo_documento_upload_to)),
                ('imagen', imagekit.models.fields.ProcessedImageField(db_column='img', null=True, upload_to=postventa.models.postventa_evento_equipo_documento_upload_to)),
                ('creado_por', models.ForeignKey(blank=True, db_column='crt_by', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(db_column='equ', on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='proyectos_equipos.EquipoProyecto')),
            ],
            options={
                'db_table': 'postventa_even_equip_docs',
                'permissions': [('list_postventaeventoequipodocumento', 'Can list documentos evento postventa equipo')],
            },
        ),
        migrations.CreateModel(
            name='PostventaEventoEquipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('descripcion', models.TextField(db_column='desc')),
                ('fecha_solicitud', models.DateField(db_column='fec_sol')),
                ('fecha_inicial', models.DateField(db_column='fec_ini')),
                ('fecha_final', models.DateField(db_column='fec_fin', null=True)),
                ('tipo', models.CharField(choices=[('NUMBER', 'Número'), ('TEXT', 'Texto'), ('LIST', 'Lista')], max_length=120)),
                ('estado', models.CharField(choices=[('SOL', 'Solicitado'), ('PRO', 'En Proceso'), ('FIN', 'Finalizado')], max_length=120)),
                ('creado_por', models.ForeignKey(blank=True, db_column='crt_by', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
