# Generated by Django 2.2.6 on 2020-09-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postventa', '0002_auto_20200905_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='postventagarantia',
            name='descripcion',
            field=models.TextField(db_column='desc', default='migrado'),
            preserve_default=False,
        ),
    ]
