# Generated by Django 2.2.6 on 2020-09-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postventa', '0003_postventagarantia_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='postventaeventoequipo',
            name='tecnico_a_cargo',
            field=models.CharField(db_column='tec_a_car', default='carlos', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postventaeventoequipo',
            name='tipo',
            field=models.CharField(choices=[('MONTAJE', 'Montaje'), ('MODIFICACION', 'Modificación'), ('GARANTIA', 'Garantía'), ('AJUSTE', 'Ajuste'), ('ASISTENCIA_TECNICA', 'Asistencia Técnica'), ('REPARACION', 'Reparación')], max_length=120),
        ),
    ]
