# Generated by Django 2.2.6 on 2020-09-06 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_equipos', '0012_auto_20200905_1011'),
        ('postventa', '0004_auto_20200906_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='postventaeventoequipo',
            name='equipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_servicio', to='proyectos_equipos.EquipoProyecto'),
            preserve_default=False,
        ),
    ]
