# Generated by Django 2.2.6 on 2020-09-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postventa', '0005_postventaeventoequipo_equipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postventaeventoequipo',
            old_name='fecha_inicial',
            new_name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='postventaeventoequipo',
            name='fecha_final',
        ),
        migrations.AddField(
            model_name='postventaeventoequipo',
            name='fecha_terminacion',
            field=models.DateField(db_column='fec_ter', null=True),
        ),
    ]
