# Generated by Django 2.2.6 on 2020-09-10 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postventa', '0007_auto_20200909_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postventaeventoequipodocumento',
            name='equipo',
        ),
        migrations.AddField(
            model_name='postventaeventoequipodocumento',
            name='evento',
            field=models.ForeignKey(db_column='equ', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='postventa.PostventaEventoEquipo'),
            preserve_default=False,
        ),
    ]
