# Generated by Django 2.2.6 on 2020-09-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postventa', '0008_auto_20200909_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postventaeventoequipo',
            name='tecnico_a_cargo',
            field=models.CharField(db_column='tec_a_car', max_length=200, null=True),
        ),
    ]
