# Generated by Django 2.0.4 on 2019-04-11 16:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0048_auto_20190123_1043'),
        ('cargues_catalogos', '0004_auto_20190411_1116'),
        ('sistema_informacion_origen', '0003_sistemainformacionorigen_codigo_amarre'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fecha_documento', models.DateField(null=True)),
                ('direccion_despacho', models.CharField(max_length=400, null=True)),
                ('tipo_documento', models.CharField(max_length=3, null=True)),
                ('nro_documento', models.CharField(max_length=10, null=True)),
                ('venta_bruta', models.DecimalField(decimal_places=4, max_digits=18)),
                ('dscto_netos', models.DecimalField(decimal_places=4, max_digits=18)),
                ('costo_total', models.DecimalField(decimal_places=4, max_digits=18)),
                ('rentabilidad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('imp_netos', models.DecimalField(decimal_places=4, max_digits=18)),
                ('venta_neto', models.DecimalField(decimal_places=4, max_digits=18)),
                ('activa', models.BooleanField(default=True)),
                ('ciudad_biable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cargues_catalogos.CiudadCatalogo')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='cargues_catalogos.ClienteCatalogo')),
                ('sistema_informacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistema_informacion_origen.SistemaInformacionOrigen')),
                ('sucursal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='cargues_catalogos.SucursalCatalogo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemsLiteralDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lapso', models.DateField()),
                ('cantidad', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('costo_total', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cargues_catalogos.ItemsCatalogo')),
                ('literal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='proyectos.Literal', verbose_name='items')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoVentaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=3, null=True)),
                ('nro_documento', models.CharField(max_length=10, null=True)),
                ('precio_uni', models.DecimalField(decimal_places=4, max_digits=18)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('venta_bruta', models.DecimalField(decimal_places=4, max_digits=18)),
                ('dscto_netos', models.DecimalField(decimal_places=4, max_digits=18)),
                ('costo_total', models.DecimalField(decimal_places=4, max_digits=18)),
                ('rentabilidad', models.DecimalField(decimal_places=4, max_digits=18)),
                ('imp_netos', models.DecimalField(decimal_places=4, max_digits=18)),
                ('venta_neto', models.DecimalField(decimal_places=4, max_digits=18)),
                ('proyecto', models.CharField(max_length=60, null=True)),
                ('factura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='cargues_detalles.FacturaDetalle')),
                ('item_biable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='cargues_catalogos.ItemsCatalogo')),
                ('sistema_informacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistema_informacion_origen.SistemaInformacionOrigen')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='itemsliteraldetalle',
            unique_together={('item', 'literal', 'lapso')},
        ),
    ]
