# Generated by Django 2.0.4 on 2019-04-11 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_catalogos', '0005_auto_20190411_1155'),
        ('cargues_detalles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturadetalle',
            name='colaborador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='cargues_catalogos.ColaboradorCatalogo'),
        ),
        migrations.AlterField(
            model_name='movimientoventadetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='movimientoventadetalle',
            name='costo_total',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='movimientoventadetalle',
            name='dscto_netos',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='movimientoventadetalle',
            name='imp_netos',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='movimientoventadetalle',
            name='precio_uni',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='movimientoventadetalle',
            name='rentabilidad',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='movimientoventadetalle',
            name='venta_bruta',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='movimientoventadetalle',
            name='venta_neto',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
    ]
