# Generated by Django 2.0.4 on 2019-04-15 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_detalles', '0002_auto_20190411_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturadetalle',
            old_name='ciudad_biable',
            new_name='ciudad',
        ),
        migrations.RenameField(
            model_name='movimientoventadetalle',
            old_name='item_biable',
            new_name='item',
        ),
    ]
