# Generated by Django 2.2.6 on 2020-02-07 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_catalogos', '0033_auto_20200207_0953'),
        ('cargues_detalles', '0004_auto_20200205_1827'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movimientoventadetalle',
            unique_together={('factura', 'item')},
        ),
        migrations.RemoveField(
            model_name='movimientoventadetalle',
            name='proyecto',
        ),
    ]
