# Generated by Django 2.2.6 on 2020-02-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_detalles', '0005_auto_20200207_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturadetalle',
            name='fecha_documento',
            field=models.DateTimeField(null=True),
        ),
    ]
