# Generated by Django 2.2.6 on 2020-02-23 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_detalles', '0006_auto_20200221_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientoventadetalle',
            options={'permissions': [('list_movimientoventadetalle', 'Can list movimiento venta detalle')]},
        ),
    ]
