# Generated by Django 2.2.6 on 2020-02-24 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_detalles', '0007_auto_20200223_0734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturadetalle',
            options={'permissions': [('list_facturadetalle', 'Can list factura detalle')]},
        ),
    ]
