# Generated by Django 2.2.6 on 2020-02-24 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0004_auto_20200217_0824'),
        ('cargues_detalles', '0009_auto_20200224_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturadetalle',
            name='colaborador_original',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_vendedor_sistema', to='colaboradores.Colaborador'),
        ),
        migrations.AlterField(
            model_name='facturadetalle',
            name='colaborador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_vendedor_original', to='colaboradores.Colaborador'),
        ),
    ]
