# Generated by Django 2.2.6 on 2020-02-25 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_detalles', '0011_itemsliteraldetalle_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsliteraldetalle',
            name='estado',
        ),
    ]
