# Generated by Django 2.2.6 on 2020-02-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_detalles', '0012_remove_itemsliteraldetalle_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturadetalle',
            name='fecha_documento',
            field=models.DateField(null=True),
        ),
    ]
