# Generated by Django 2.2.6 on 2020-03-03 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_detalles', '0013_auto_20200227_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturadetalle',
            options={'permissions': [('list_facturadetalle', 'Can list factura detalle'), ('see_costos_facturadetalle', 'Can see costos factura detalle'), ('see_rentabilidad_facturadetalle', 'Can see rentabilidad factura detalle'), ('see_descuentos_facturadetalle', 'Can see descuentos factura detalle'), ('relacionar_cotizacion_componentes_facturadetalle', 'Can relacionar cotizacion componentes')]},
        ),
    ]
