# Generated by Django 2.2.6 on 2020-04-15 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_detalles', '0014_auto_20200303_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientoventadetalle',
            options={'permissions': [('list_movimientoventadetalle', 'Can list movimiento venta detalle'), ('see_costos_movimientoventadetalle', 'Can see movimiento venta detalle'), ('see_rentabilidad_movimientoventadetalle', 'Can see movimiento venta detalle'), ('see_descuentos_movimientoventadetalle', 'Can see movimiento venta detalle')]},
        ),
    ]
