# Generated by Django 2.2.6 on 2020-07-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_detalles', '0016_movimientoventadetalle_unidad_medida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturadetalle',
            options={'permissions': [('list_facturadetalle', 'Can list factura detalle'), ('see_costos_facturadetalle', 'Can see costos factura detalle'), ('see_rentabilidad_facturadetalle', 'Can see rentabilidad factura detalle'), ('see_descuentos_facturadetalle', 'Can see descuentos factura detalle'), ('relacionar_cotizacion_componentes_facturadetalle', 'Can relacionar cotizacion componentes'), ('set_no_afecta_ingreso_facturadetalle', 'Definir si afecta ingreso factura detalle')]},
        ),
        migrations.AlterModelOptions(
            name='movimientoventadetalle',
            options={'permissions': [('list_movimientoventadetalle', 'Can list movimiento venta detalle'), ('see_costos_movimientoventadetalle', 'Can see movimiento venta detalle'), ('see_rentabilidad_movimientoventadetalle', 'Can see movimiento venta detalle'), ('see_descuentos_movimientoventadetalle', 'Can see movimiento venta detalle'), ('set_no_afecta_ingreso_movimientoventadetalle', 'Definir si afecta ingreso movimiento venta detalle')]},
        ),
        migrations.AddField(
            model_name='facturadetalle',
            name='no_afecta_ingreso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimientoventadetalle',
            name='no_afecta_ingreso',
            field=models.BooleanField(default=False),
        ),
    ]
