# Generated by Django 2.2.6 on 2020-07-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_detalles', '0017_auto_20200702_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturadetalle',
            name='tipo_documento_real',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
