# Generated by Django 2.2.6 on 2020-07-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_detalles', '0018_facturadetalle_tipo_documento_real'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturadetalle',
            old_name='tipo_documento_real',
            new_name='tipo_documento_original',
        ),
    ]
