# Generated by Django 2.2.6 on 2020-07-03 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cargues_detalles', '0020_auto_20200703_1056'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facturadetalle',
            unique_together=set(),
        ),
    ]
