# Generated by Django 2.0.4 on 2019-05-28 13:02

from django.db import migrations, models
import medios_adhesivos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adhesivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('alto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ancho', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('color', models.CharField(max_length=10, null=True)),
                ('stock_min', models.IntegerField(default=0, null=True)),
                ('descripcion', models.CharField(max_length=500, null=True)),
                ('imagen', models.FileField(null=True, upload_to=medios_adhesivos.models.Adhesivo.archivo_upload_to)),
                ('sticker', models.BooleanField()),
            ],
        ),
    ]
