# Generated by Django 2.0.4 on 2019-05-29 19:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('medios_adhesivos', '0002_auto_20190528_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdhesivoMovimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida')], max_length=1)),
                ('responsable', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200, null=True)),
                ('saldo', models.IntegerField()),
                ('ultimo', models.BooleanField()),
                ('adhesivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='medios_adhesivos.Adhesivo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
