# Generated by Django 2.2 on 2019-05-31 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medios_adhesivos', '0003_adhesivomovimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhesivomovimiento',
            name='adhesivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='medios_adhesivos.Adhesivo'),
        ),
    ]
