# Generated by Django 2.2 on 2019-06-04 15:49

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import medios_adhesivos.models


class Migration(migrations.Migration):

    dependencies = [
        ('medios_adhesivos', '0004_auto_20190531_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhesivo',
            name='imagen',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=medios_adhesivos.models.Adhesivo.archivo_upload_to),
        ),
        migrations.AlterField(
            model_name='adhesivomovimiento',
            name='adhesivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='medios_adhesivos.Adhesivo'),
        ),
    ]
