# Generated by Django 2.2 on 2019-06-04 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medios_adhesivos', '0006_auto_20190604_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adhesivomovimiento',
            options={'permissions': [('list_adhesivomovimiento', 'Can list adhesivo movimiento '), ('list_inventario_adhesivomovimiento', 'Can list adhesivo movimiento inventario')]},
        ),
    ]
