# Generated by Django 2.2 on 2019-06-07 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medios_adhesivos', '0007_auto_20190604_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhesivomovimiento',
            name='creado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_adhesivos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
