# Generated by Django 2.2 on 2019-06-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medios_adhesivos', '0008_adhesivomovimiento_creado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhesivomovimiento',
            name='responsable',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
