# Generated by Django 2.0.4 on 2018-09-07 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0040_auto_20180612_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='FaseLiteral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyectos_seguimientos.Fase')),
                ('literal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyectos.Literal')),
            ],
        ),
        migrations.CreateModel(
            name='TareaFase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_limite', models.DateField()),
                ('descripcion', models.CharField(max_length=500)),
                ('terminado', models.BooleanField(default=False)),
                ('fase_literal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareas', to='proyectos_seguimientos.FaseLiteral')),
            ],
        ),
        migrations.AddField(
            model_name='fase',
            name='literales',
            field=models.ManyToManyField(through='proyectos_seguimientos.FaseLiteral', to='proyectos.Literal'),
        ),
    ]
