# Generated by Django 2.0.4 on 2018-09-11 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_seguimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fase',
            options={'permissions': [('list_fase', 'Can see list fases')]},
        ),
    ]
