# Generated by Django 2.0.4 on 2018-09-11 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_seguimientos', '0002_auto_20180911_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faseliteral',
            name='fase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_literales', to='proyectos_seguimientos.Fase'),
        ),
        migrations.AlterField(
            model_name='faseliteral',
            name='literal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_fases', to='proyectos.Literal'),
        ),
    ]
