# Generated by Django 2.0.4 on 2018-09-26 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos_seguimientos', '0003_auto_20180911_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareafase',
            name='asignado_a',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tareas_seguimiento_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tareafase',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tareas_seguimiento_a_revisar', to=settings.AUTH_USER_MODEL),
        ),
    ]
