# Generated by Django 2.0.4 on 2018-09-26 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_seguimientos', '0006_auto_20180926_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faseliteral',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fases_a_revisar', to=settings.AUTH_USER_MODEL),
        ),
    ]
