# Generated by Django 2.0.4 on 2018-10-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_seguimientos', '0007_auto_20180926_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareafase',
            name='estado',
            field=models.PositiveIntegerField(choices=[(0, 'PENDIENTE'), (1, 'EN PROCESO'), (2, 'TERMINADO')], default=0),
        ),
    ]
