# Generated by Django 2.0.4 on 2018-10-03 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_seguimientos', '0008_tareafase_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareafase',
            name='terminado',
        ),
    ]
