# Generated by Django 2.0.4 on 2018-10-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_seguimientos', '0009_remove_tareafase_terminado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareafase',
            name='estado',
            field=models.PositiveIntegerField(choices=[(1, 'NUEVA'), (2, 'PENDIENTE'), (3, 'EN PROCESO'), (4, 'TERMINADO')], default=0),
        ),
    ]
