# Generated by Django 2.0.4 on 2018-10-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_seguimientos', '0011_auto_20181010_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareafase',
            name='estado',
            field=models.PositiveIntegerField(choices=[(1, 'NUEVA'), (2, 'PENDIENTE'), (3, 'EN PROCESO'), (4, 'TERMINADO')], default=1),
        ),
    ]
