# Generated by Django 2.0.4 on 2018-10-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_seguimientos', '0012_auto_20181011_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareafase',
            name='campo_dos',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tareafase',
            name='campo_tres',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tareafase',
            name='campo_uno',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
