# Generated by Django 2.1.4 on 2018-12-29 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_seguimientos', '0013_auto_20181011_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareafase',
            name='fecha_inicial',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
