# Generated by Django 2.1.4 on 2019-01-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_seguimientos', '0014_tareafase_fecha_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareafase',
            name='campo_dos',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tareafase',
            name='campo_tres',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tareafase',
            name='campo_uno',
            field=models.CharField(default='', max_length=200),
        ),
    ]
