# Generated by Django 2.1.4 on 2019-01-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_seguimientos', '0015_auto_20190110_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='fase',
            name='color',
            field=models.CharField(default='', max_length=10),
        ),
    ]
