# Generated by Django 2.1.4 on 2019-01-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_seguimientos', '0017_fase_letra_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase',
            name='letra_color',
            field=models.CharField(default='black', max_length=10),
        ),
    ]
