# Generated by Django 2.1.4 on 2019-01-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_seguimientos', '0018_auto_20190111_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase',
            name='color',
            field=models.CharField(default='black', max_length=10),
        ),
        migrations.AlterField(
            model_name='fase',
            name='letra_color',
            field=models.CharField(default='white', max_length=10),
        ),
    ]
