# Generated by Django 2.0.4 on 2019-01-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_seguimientos', '0019_auto_20190111_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='fase',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
