# Generated by Django 2.0.4 on 2019-04-05 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistema_informacion_origen', '0003_sistemainformacionorigen_codigo_amarre'),
        ('geografia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CiudadCatalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad_id', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=120)),
                ('ciudad_intranet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='geografia.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='DepartamentoCatalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento_id', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='PaisCatalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais_id', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=120)),
                ('sistema_informacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistema_informacion_origen.SistemaInformacionOrigen')),
            ],
        ),
        migrations.AddField(
            model_name='departamentocatalogo',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cargues_catalogos.PaisCatalogo'),
        ),
        migrations.AddField(
            model_name='departamentocatalogo',
            name='sistema_informacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistema_informacion_origen.SistemaInformacionOrigen'),
        ),
        migrations.AddField(
            model_name='ciudadcatalogo',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cargues_catalogos.DepartamentoCatalogo'),
        ),
        migrations.AddField(
            model_name='ciudadcatalogo',
            name='sistema_informacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistema_informacion_origen.SistemaInformacionOrigen'),
        ),
        migrations.AlterUniqueTogether(
            name='paiscatalogo',
            unique_together={('sistema_informacion', 'pais_id')},
        ),
        migrations.AlterUniqueTogether(
            name='departamentocatalogo',
            unique_together={('sistema_informacion', 'departamento_id')},
        ),
        migrations.AlterUniqueTogether(
            name='ciudadcatalogo',
            unique_together={('sistema_informacion', 'ciudad_id')},
        ),
    ]
