# Generated by Django 2.0.4 on 2019-04-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_catalogos', '0002_auto_20190408_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientecatalogo',
            name='forma_pago',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
