# Generated by Django 2.0.4 on 2019-04-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_catalogos', '0005_auto_20190411_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradorcatalogo',
            name='es_vendedor',
            field=models.BooleanField(default=False),
        ),
    ]
