# Generated by Django 2.0.4 on 2019-04-11 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_catalogos', '0006_colaboradorcatalogo_es_vendedor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LineaVendedorBiable',
            new_name='LineaVendedorCatalogo',
        ),
    ]
