# Generated by Django 2.0.4 on 2019-04-11 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_catalogos', '0007_auto_20190411_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaboradorcentrocostocatalogo',
            name='linea',
        ),
        migrations.AddField(
            model_name='colaboradorcatalogo',
            name='linea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cargues_catalogos.LineaVendedorCatalogo'),
        ),
    ]
