# Generated by Django 2.0.4 on 2019-04-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_catalogos', '0009_auto_20190412_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaboradorcatalogo',
            name='sistema_informacion',
        ),
        migrations.AlterField(
            model_name='clientecatalogo',
            name='nit',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='clientecatalogo',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='clientecatalogo',
            name='sistema_informacion',
        ),
    ]
