# Generated by Django 2.2 on 2019-08-09 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_auto_20190809_1105'),
        ('sistema_informacion_origen', '0004_auto_20190610_1453'),
        ('cargues_catalogos', '0012_auto_20190610_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientecatalogo',
            name='cliente_contacto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.ClienteBiable'),
        ),
        migrations.AddField(
            model_name='clientecatalogo',
            name='sistema_informacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sistema_informacion_origen.SistemaInformacionOrigen'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='clientecatalogo',
            unique_together={('sistema_informacion', 'nit')},
        ),
        migrations.RemoveField(
            model_name='clientecatalogo',
            name='canal',
        ),
        migrations.RemoveField(
            model_name='clientecatalogo',
            name='cliente_nuevo_nit',
        ),
        migrations.RemoveField(
            model_name='clientecatalogo',
            name='es_competencia',
        ),
        migrations.RemoveField(
            model_name='clientecatalogo',
            name='esta_cerrado',
        ),
        migrations.RemoveField(
            model_name='clientecatalogo',
            name='forma_pago',
        ),
        migrations.RemoveField(
            model_name='clientecatalogo',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='clientecatalogo',
            name='industria',
        ),
        migrations.RemoveField(
            model_name='clientecatalogo',
            name='no_vender',
        ),
    ]
