# Generated by Django 2.2 on 2019-08-09 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_catalogos', '0013_auto_20190809_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientecatalogo',
            name='cliente_contacto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes_sistemas_informacion', to='clientes.ClienteBiable'),
        ),
    ]
