# Generated by Django 2.2.6 on 2019-12-16 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_catalogos', '0014_auto_20190809_1220'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ciudadcatalogo',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='departamentocatalogo',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='paiscatalogo',
            unique_together=set(),
        ),
    ]
