# Generated by Django 2.2.6 on 2019-12-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_catalogos', '0015_auto_20191216_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientecatalogo',
            name='nit',
            field=models.CharField(max_length=20),
        ),
    ]
