# Generated by Django 2.2.6 on 2019-12-17 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_catalogos', '0016_auto_20191216_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudadcatalogo',
            name='ciudad_intranet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ciudad_catalogo', to='geografia.Ciudad'),
        ),
    ]
