# Generated by Django 2.2.6 on 2020-01-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_catalogos', '0017_auto_20191216_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemscatalogo',
            name='desc_item_padre',
            field=models.CharField(max_length=400),
        ),
    ]
