# Generated by Django 2.2.6 on 2020-01-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_catalogos', '0018_auto_20200120_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargueControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedimiento_nombre', models.CharField(max_length=400)),
                ('tarea', models.CharField(max_length=400)),
                ('fecha', models.DateTimeField()),
                ('numero_filas', models.BigIntegerField()),
                ('cuenta', models.BigIntegerField()),
            ],
        ),
    ]
