# Generated by Django 2.2.6 on 2020-01-28 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_catalogos', '0019_carguecontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoCargue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoCargueProcedimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedimiento_nombre', models.CharField(max_length=400)),
                ('tarea', models.CharField(max_length=400)),
                ('fecha', models.DateTimeField()),
                ('numero_filas', models.BigIntegerField()),
                ('cargue_contro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedimientos', to='cargues_catalogos.SeguimientoCargue')),
            ],
        ),
        migrations.DeleteModel(
            name='CargueControl',
        ),
    ]
