# Generated by Django 2.2.6 on 2020-01-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_catalogos', '0022_seguimientocargueprocedimiento_tabla'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientocargue',
            name='fecha_final',
            field=models.DateTimeField(null=True),
        ),
    ]
