# Generated by Django 2.2.6 on 2020-01-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_catalogos', '0023_seguimientocargue_fecha_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientecatalogo',
            name='id_tercero',
            field=models.BigIntegerField(null=True),
        ),
    ]
