# Generated by Django 2.2.6 on 2020-01-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_catalogos', '0025_auto_20200129_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradorcentrocostocatalogo',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
    ]
