# Generated by Django 2.2.6 on 2020-01-30 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_informacion_origen', '0004_auto_20190610_1453'),
        ('colaboradores', '0001_initial'),
        ('cargues_catalogos', '0026_auto_20200130_0723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaboradorcatalogo',
            options={'permissions': [('list_colaboradorcatalogo', 'Can see list colaboradores catalogos')]},
        ),
        migrations.AddField(
            model_name='colaboradorcatalogo',
            name='colaborador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='colaborador_sistema_informacion', to='colaboradores.Colaborador'),
        ),
        migrations.AddField(
            model_name='colaboradorcatalogo',
            name='sistema_informacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sistema_informacion_origen.SistemaInformacionOrigen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colaboradorcatalogo',
            name='centro_costo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='costos_mensuales_colaboradores', to='cargues_catalogos.ColaboradorCentroCostoCatalogo'),
        ),
        migrations.AlterUniqueTogether(
            name='colaboradorcatalogo',
            unique_together={('sistema_informacion', 'cedula')},
        ),
        migrations.RemoveField(
            model_name='colaboradorcatalogo',
            name='autogestion_horas_trabajadas',
        ),
        migrations.RemoveField(
            model_name='colaboradorcatalogo',
            name='auxilio_transporte',
        ),
        migrations.RemoveField(
            model_name='colaboradorcatalogo',
            name='base_salario',
        ),
        migrations.RemoveField(
            model_name='colaboradorcatalogo',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='colaboradorcatalogo',
            name='en_proyectos',
        ),
        migrations.RemoveField(
            model_name='colaboradorcatalogo',
            name='es_aprendiz',
        ),
        migrations.RemoveField(
            model_name='colaboradorcatalogo',
            name='es_salario_fijo',
        ),
        migrations.RemoveField(
            model_name='colaboradorcatalogo',
            name='linea',
        ),
        migrations.RemoveField(
            model_name='colaboradorcatalogo',
            name='nro_horas_mes',
        ),
        migrations.RemoveField(
            model_name='colaboradorcatalogo',
            name='porcentaje_arl',
        ),
        migrations.RemoveField(
            model_name='colaboradorcatalogo',
            name='porcentaje_caja_compensacion',
        ),
        migrations.RemoveField(
            model_name='colaboradorcatalogo',
            name='porcentaje_pension',
        ),
        migrations.RemoveField(
            model_name='colaboradorcatalogo',
            name='porcentaje_prestaciones_sociales',
        ),
        migrations.RemoveField(
            model_name='colaboradorcatalogo',
            name='porcentaje_salud',
        ),
        migrations.RemoveField(
            model_name='colaboradorcatalogo',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='CargosCatalogo',
        ),
        migrations.DeleteModel(
            name='LineaVendedorCatalogo',
        ),
    ]
