# Generated by Django 2.2.6 on 2020-01-30 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_informacion_origen', '0004_auto_20190610_1453'),
        ('cargues_catalogos', '0028_auto_20200130_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaboradorcatalogo',
            name='centro_costo',
        ),
        migrations.CreateModel(
            name='CargoColaboradorCatalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_id', models.PositiveIntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('tipo_cargo', models.CharField(blank=True, max_length=300, null=True)),
                ('sistema_informacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sistema_informacion_origen.SistemaInformacionOrigen')),
            ],
        ),
    ]
