# Generated by Django 2.2.6 on 2020-01-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_catalogos', '0029_auto_20200130_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradorcatalogo',
            name='cedula',
            field=models.CharField(max_length=20),
        ),
    ]
