# Generated by Django 2.2.6 on 2020-02-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_catalogos', '0032_auto_20200203_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemscatalogo',
            name='id_item',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
