# Generated by Django 2.2.6 on 2020-02-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_catalogos', '0033_auto_20200207_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudadcatalogo',
            name='ciudad_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='departamentocatalogo',
            name='departamento_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='paiscatalogo',
            name='pais_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
