# Generated by Django 2.2.6 on 2020-02-19 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_catalogos', '0034_auto_20200207_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seguimientocargue',
            options={'permissions': [('list_seguimientocargue', 'Can list seguimientos cargues')]},
        ),
    ]
