# Generated by Django 2.2.6 on 2020-03-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_catalogos', '0037_unidadmedidacatalogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadmedidacatalogo',
            name='nomenclatura',
        ),
        migrations.AlterField(
            model_name='unidadmedidacatalogo',
            name='id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
