# Generated by Django 2.2.6 on 2020-03-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_catalogos', '0038_auto_20200310_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadmedidacatalogo',
            name='sincronizado_sistema_informacion',
            field=models.BooleanField(default=0),
        ),
    ]
