# Generated by Django 2.2.6 on 2020-03-10 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_catalogos', '0039_unidadmedidacatalogo_sincronizado_sistema_informacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidadmedidacatalogo',
            options={'permissions': [('list_unidadmedidacatalogo', 'Can list unidades medidas catalogo')]},
        ),
    ]
