# Generated by Django 2.2.6 on 2020-03-10 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_catalogos', '0040_auto_20200310_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemscatalogo',
            name='unidad_medida_en_inventario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cargues_catalogos.UnidadMedidaCatalogo'),
        ),
    ]
