# Generated by Django 2.2.6 on 2020-03-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_catalogos', '0041_itemscatalogo_unidad_medida_en_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadmedidacatalogo',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
