# Generated by Django 2.2.6 on 2020-03-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_catalogos', '0042_unidadmedidacatalogo_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemscatalogo',
            name='unidad_medida_inventario',
        ),
    ]
