# Generated by Django 2.2.6 on 2020-03-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_catalogos', '0043_remove_itemscatalogo_unidad_medida_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemscatalogo',
            name='id_referencia',
            field=models.CharField(max_length=40),
        ),
    ]
