# Generated by Django 2.2.6 on 2020-03-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_catalogos', '0044_auto_20200311_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientocargue',
            name='descripcion',
            field=models.CharField(default='Cargue Completo', max_length=400),
        ),
    ]
