# Generated by Django 2.2.6 on 2020-04-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_catalogos', '0045_seguimientocargue_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemscatalogo',
            name='marca',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
