# Generated by Django 2.0.4 on 2019-04-15 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0014_clientebiable_sistema_informacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagoCanal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(max_length=100)),
                ('porcentaje', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.CanalDistribucion')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='formapagocanal',
            unique_together={('canal', 'forma')},
        ),
    ]
