# Generated by Django 2.1.4 on 2018-12-12 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nomenclatura', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ALETA', 'Aleta'), ('EMPUJADOR', 'Empujador'), ('MODULO', 'Modulo'), ('VARILLA', 'Varilla'), ('TAPA', 'Tapa')], max_length=200)),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('alto', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('largo', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('diametro_varilla', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='componentes', to='bandas_eurobelt.Color')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoEnsamblado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_ensamblados', to='bandas_eurobelt.Color')),
                ('componentes_compatibles', models.ManyToManyField(related_name='grupos_ensamblados', to='bandas_eurobelt.Componente')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nomenclatura', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nomenclatura', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='TipoBanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nomenclatura', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='grupoensamblado',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_ensamblados', to='bandas_eurobelt.Material'),
        ),
        migrations.AddField(
            model_name='grupoensamblado',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_ensamblados', to='bandas_eurobelt.Serie'),
        ),
        migrations.AddField(
            model_name='grupoensamblado',
            name='tipo_banda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_ensamblados', to='bandas_eurobelt.TipoBanda'),
        ),
        migrations.AddField(
            model_name='componente',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='componentes', to='bandas_eurobelt.Material'),
        ),
        migrations.AddField(
            model_name='componente',
            name='series_compatibles',
            field=models.ManyToManyField(related_name='componentes', to='bandas_eurobelt.Serie'),
        ),
        migrations.AddField(
            model_name='componente',
            name='tipo_banda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='componentes', to='bandas_eurobelt.TipoBanda'),
        ),
        migrations.AlterUniqueTogether(
            name='grupoensamblado',
            unique_together={('color', 'material', 'serie', 'tipo_banda')},
        ),
    ]
