# Generated by Django 2.0.4 on 2019-05-09 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cguno', '0060_auto_20180612_1306'),
        ('importaciones', '0002_auto_20190416_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaComponenteBandaEurobelt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('nomenclatura', models.CharField(max_length=4, unique=True)),
                ('factor_importacion', models.DecimalField(decimal_places=3, default=1, max_digits=18)),
                ('factor_importacion_aereo', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('margen_deseado', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('nombre_con_categoria_uno', models.BooleanField(default=False)),
                ('nombre_con_categoria_dos', models.BooleanField(default=False)),
                ('nombre_con_serie', models.BooleanField(default=False)),
                ('nombre_con_tipo', models.BooleanField(default=False)),
                ('nombre_con_material', models.BooleanField(default=False)),
                ('nombre_con_color', models.BooleanField(default=False)),
                ('nombre_con_ancho', models.BooleanField(default=False)),
                ('nombre_con_alto', models.BooleanField(default=False)),
                ('nombre_con_longitud', models.BooleanField(default=False)),
                ('nombre_con_diametro', models.BooleanField(default=False)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias_bandas_eurobelt', to='importaciones.MonedaCambio')),
            ],
        ),
        migrations.CreateModel(
            name='ColorBandaEurobelt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('nomenclatura', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComponenteBandaEurobelt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=100, null=True)),
                ('descripcion_adicional', models.CharField(max_length=100, null=True)),
                ('ancho', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('alto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('largo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('diametro_varilla', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='componentes', to='bandas_eurobelt.CategoriaComponenteBandaEurobelt')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='componentes', to='bandas_eurobelt.ColorBandaEurobelt')),
                ('item_cguno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='componente_banda', to='cguno.ItemsBiable')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoEnsambladoBandaEurobelt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_ensamblados', to='bandas_eurobelt.ColorBandaEurobelt')),
                ('componentes_compatibles', models.ManyToManyField(related_name='grupos_ensamblados', to='bandas_eurobelt.ComponenteBandaEurobelt')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialBandaEurobelt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('nomenclatura', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SerieBandaEurobelt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('nomenclatura', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoBandaBandaEurobelt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('nomenclatura', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='grupoensambladobandaeurobelt',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_ensamblados', to='bandas_eurobelt.MaterialBandaEurobelt'),
        ),
        migrations.AddField(
            model_name='grupoensambladobandaeurobelt',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_ensamblados', to='bandas_eurobelt.SerieBandaEurobelt'),
        ),
        migrations.AddField(
            model_name='grupoensambladobandaeurobelt',
            name='tipo_banda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_ensamblados', to='bandas_eurobelt.TipoBandaBandaEurobelt'),
        ),
        migrations.AddField(
            model_name='componentebandaeurobelt',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='componentes', to='bandas_eurobelt.MaterialBandaEurobelt'),
        ),
        migrations.AddField(
            model_name='componentebandaeurobelt',
            name='series_compatibles',
            field=models.ManyToManyField(related_name='componentes', to='bandas_eurobelt.SerieBandaEurobelt'),
        ),
        migrations.AddField(
            model_name='componentebandaeurobelt',
            name='tipo_banda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='componentes', to='bandas_eurobelt.TipoBandaBandaEurobelt'),
        ),
        migrations.AlterUniqueTogether(
            name='grupoensambladobandaeurobelt',
            unique_together={('color', 'material', 'serie', 'tipo_banda')},
        ),
    ]
