# Generated by Django 2.1.4 on 2018-12-12 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandas_eurobelt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componente',
            old_name='nombre',
            new_name='descripcion_adicional',
        ),
    ]
