# Generated by Django 2.0.4 on 2019-05-15 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandas_eurobelt', '0002_auto_20190515_0724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriadoscomponentebandaeurobelt',
            options={'permissions': [('list_categoriadoscomponentebandaeurobelt', 'Can see list categorias dos eurobelt')]},
        ),
    ]
