# Generated by Django 2.0.4 on 2019-05-15 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20190515_0755'),
        ('bandas_eurobelt', '0003_auto_20190515_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNombreAutomatico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_con_categoria_uno', models.BooleanField(default=False)),
                ('nombre_con_categoria_dos', models.BooleanField(default=False)),
                ('nombre_con_tipo', models.BooleanField(default=False)),
                ('nombre_con_serie', models.BooleanField(default=False)),
                ('nombre_con_material', models.BooleanField(default=False)),
                ('nombre_con_color', models.BooleanField(default=False)),
                ('nombre_con_ancho', models.BooleanField(default=False)),
                ('nombre_con_alto', models.BooleanField(default=False)),
                ('nombre_con_longitud', models.BooleanField(default=False)),
                ('nombre_con_diametro', models.BooleanField(default=False)),
                ('categoria', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nombre_automatico_erobelt', to='items.CategoriaProducto')),
            ],
        ),
        migrations.RemoveField(
            model_name='componentebandaeurobelt',
            name='categoria',
        ),
        migrations.AddField(
            model_name='categoriadoscomponentebandaeurobelt',
            name='categorias',
            field=models.ManyToManyField(related_name='categorias_dos_eurobelt', to='items.CategoriaProducto'),
        ),
        migrations.AddField(
            model_name='componentebandaeurobelt',
            name='categoria_dos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='componentes', to='bandas_eurobelt.CategoriaDosComponenteBandaEurobelt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipobandabandaeurobelt',
            name='categorias',
            field=models.ManyToManyField(related_name='tipos_eurobelt', to='items.CategoriaProducto'),
        ),
        migrations.DeleteModel(
            name='CategoriaComponenteBandaEurobelt',
        ),
    ]
