# Generated by Django 2.2 on 2019-07-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas_eurobelt', '0004_auto_20190515_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentebandaeurobelt',
            name='descripcion_automatica',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
