# Generated by Django 2.1.4 on 2018-12-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas_eurobelt', '0004_componente_item_cguno'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
