# Generated by Django 2.2 on 2019-07-31 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandas_eurobelt', '0005_componentebandaeurobelt_descripcion_automatica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentebandaeurobelt',
            name='descripcion_automatica',
        ),
    ]
