# Generated by Django 2.1.4 on 2018-12-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas_eurobelt', '0005_componente_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
