# Generated by Django 2.2 on 2019-08-01 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20190515_0755'),
        ('bandas_eurobelt', '0006_remove_componentebandaeurobelt_descripcion_automatica'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentebandaeurobelt',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='componentes', to='items.CategoriaProducto'),
            preserve_default=False,
        ),
    ]
