# Generated by Django 2.1.4 on 2018-12-12 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandas_eurobelt', '0006_auto_20181212_1455'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serie',
            unique_together={('nombre', 'nomenclatura')},
        ),
    ]
