# Generated by Django 2.1.4 on 2018-12-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas_eurobelt', '0007_auto_20181212_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='nomenclatura',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='nomenclatura',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='serie',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='serie',
            name='nomenclatura',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='tipobanda',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tipobanda',
            name='nomenclatura',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='serie',
            unique_together=set(),
        ),
    ]
