# Generated by Django 2.0.4 on 2019-04-23 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0060_auto_20180612_1306'),
        ('bandas_eurobelt', '0008_auto_20181212_1501'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Serie',
            new_name='ColorBandaEurobelt',
        ),
        migrations.RenameModel(
            old_name='Componente',
            new_name='ComponenteBandaEurobelt',
        ),
        migrations.RenameModel(
            old_name='GrupoEnsamblado',
            new_name='GrupoEnsambladoBandaEurobelt',
        ),
        migrations.RenameModel(
            old_name='Color',
            new_name='MaterialBandaEurobelt',
        ),
        migrations.RenameModel(
            old_name='TipoBanda',
            new_name='SerieBandaEurobelt',
        ),
        migrations.RenameModel(
            old_name='Material',
            new_name='TipoBandaBandaEurobelt',
        ),
    ]
