# Generated by Django 2.0.4 on 2019-04-23 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0002_auto_20190416_1051'),
        ('bandas_eurobelt', '0009_auto_20190423_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaComponenteBandaEurobelt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('nomenclatura', models.CharField(max_length=4, unique=True)),
                ('margen_deseado', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias_bandas_eurobelt', to='importaciones.MonedaCambio')),
            ],
        ),
        migrations.RemoveField(
            model_name='componentebandaeurobelt',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='componentebandaeurobelt',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='componentes', to='bandas_eurobelt.ColorBandaEurobelt'),
        ),
        migrations.AlterField(
            model_name='componentebandaeurobelt',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='componentes', to='bandas_eurobelt.MaterialBandaEurobelt'),
        ),
        migrations.AlterField(
            model_name='componentebandaeurobelt',
            name='series_compatibles',
            field=models.ManyToManyField(related_name='componentes', to='bandas_eurobelt.SerieBandaEurobelt'),
        ),
        migrations.AlterField(
            model_name='componentebandaeurobelt',
            name='tipo_banda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='componentes', to='bandas_eurobelt.TipoBandaBandaEurobelt'),
        ),
        migrations.AlterField(
            model_name='grupoensambladobandaeurobelt',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_ensamblados', to='bandas_eurobelt.ColorBandaEurobelt'),
        ),
        migrations.AlterField(
            model_name='grupoensambladobandaeurobelt',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_ensamblados', to='bandas_eurobelt.MaterialBandaEurobelt'),
        ),
        migrations.AlterField(
            model_name='grupoensambladobandaeurobelt',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_ensamblados', to='bandas_eurobelt.SerieBandaEurobelt'),
        ),
        migrations.AlterField(
            model_name='grupoensambladobandaeurobelt',
            name='tipo_banda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_ensamblados', to='bandas_eurobelt.TipoBandaBandaEurobelt'),
        ),
        migrations.AddField(
            model_name='componentebandaeurobelt',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='componentes', to='bandas_eurobelt.CategoriaComponenteBandaEurobelt'),
            preserve_default=False,
        ),
    ]
