# Generated by Django 2.0.4 on 2019-04-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas_eurobelt', '0010_auto_20190423_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentebandaeurobelt',
            name='nombre',
            field=models.CharField(default='hola', max_length=100),
            preserve_default=False,
        ),
    ]
