# Generated by Django 2.0.4 on 2019-04-23 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandas_eurobelt', '0011_componentebandaeurobelt_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentebandaeurobelt',
            name='nombre',
        ),
    ]
