# Generated by Django 2.0.4 on 2019-04-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas_eurobelt', '0012_remove_componentebandaeurobelt_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentebandaeurobelt',
            name='referencia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='componentebandaeurobelt',
            name='alto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='componentebandaeurobelt',
            name='ancho',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='componentebandaeurobelt',
            name='diametro_varilla',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='componentebandaeurobelt',
            name='largo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
