# Generated by Django 2.0.4 on 2019-04-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas_eurobelt', '0013_auto_20190423_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriacomponentebandaeurobelt',
            name='factor_importacion',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name='categoriacomponentebandaeurobelt',
            name='factor_importacion_aereo',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
    ]
