# Generated by Django 2.0.4 on 2019-04-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas_eurobelt', '0014_auto_20190423_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriacomponentebandaeurobelt',
            name='nombre_con_alto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoriacomponentebandaeurobelt',
            name='nombre_con_ancho',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoriacomponentebandaeurobelt',
            name='nombre_con_categoria_dos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoriacomponentebandaeurobelt',
            name='nombre_con_categoria_uno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoriacomponentebandaeurobelt',
            name='nombre_con_color',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoriacomponentebandaeurobelt',
            name='nombre_con_diametro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoriacomponentebandaeurobelt',
            name='nombre_con_longitud',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoriacomponentebandaeurobelt',
            name='nombre_con_material',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoriacomponentebandaeurobelt',
            name='nombre_con_serie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoriacomponentebandaeurobelt',
            name='nombre_con_tipo',
            field=models.BooleanField(default=False),
        ),
    ]
