# Generated by Django 2.2 on 2019-08-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas_eurobelt', '0017_auto_20190806_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentebandaeurobelt',
            name='nombre',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
