# Generated by Django 2.2 on 2019-08-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas_eurobelt', '0019_auto_20190806_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandaeurobelt',
            name='referencia',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
