# Generated by Django 2.2.6 on 2020-02-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas_eurobelt', '0021_auto_20200130_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentebandaeurobelt',
            name='componente_banda_eurobelt_temporal',
            field=models.BigIntegerField(null=True),
        ),
    ]
