# Generated by Django 2.2.6 on 2020-02-12 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandas_eurobelt', '0022_componentebandaeurobelt_componente_banda_eurobelt_temporal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentebandaeurobelt',
            name='componente_banda_eurobelt_temporal',
        ),
    ]
