# Generated by Django 2.2.6 on 2020-02-13 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20190515_0755'),
        ('bandas_eurobelt', '0023_remove_componentebandaeurobelt_componente_banda_eurobelt_temporal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipobandabandaeurobelt',
            name='categorias',
        ),
        migrations.AlterField(
            model_name='bandaeurobelt',
            name='aleta_identacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bandaeurobelt',
            name='empujador_identacion',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='TipoBandaCategoriaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos_bandas', to='items.CategoriaProducto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias_productos', to='bandas_eurobelt.TipoBandaBandaEurobelt')),
            ],
        ),
    ]
