# Generated by Django 2.2.6 on 2020-02-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20190515_0755'),
        ('bandas_eurobelt', '0024_auto_20200213_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipobandabandaeurobelt',
            name='categorias',
            field=models.ManyToManyField(related_name='tipos_eurobelt', through='bandas_eurobelt.TipoBandaCategoriaProducto', to='items.CategoriaProducto'),
        ),
    ]
