# Generated by Django 2.2.6 on 2020-02-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas_eurobelt', '0025_tipobandabandaeurobelt_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandaeurobelt',
            name='nombre',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='bandaeurobelt',
            name='referencia',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
