# Generated by Django 2.2.6 on 2020-02-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas_eurobelt', '0026_auto_20200215_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandaeurobelt',
            name='aleta_identacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bandaeurobelt',
            name='empujador_identacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
