# Generated by Django 2.2.6 on 2020-02-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas_eurobelt', '0027_auto_20200217_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentebandaeurobelt',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
