# Generated by Django 2.0.1 on 2018-02-05 15:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cguno', '0009_auto_20180130_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasaHora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('mes', models.PositiveIntegerField()),
                ('ano', models.PositiveIntegerField()),
                ('costo_hora', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_tasas', to='cguno.ColaboradorBiable')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tasahora',
            unique_together={('mes', 'ano')},
        ),
    ]
