# Generated by Django 2.0.1 on 2018-02-05 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mano_obra', '0003_auto_20180205_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasahora',
            options={'permissions': [('list_tasas_horas_hombres', 'Can see list tasas horas hombres')]},
        ),
    ]
