# Generated by Django 2.0.1 on 2018-02-05 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cguno', '0010_colaboradorbiable_autogestion_horas_trabajadas'),
        ('mano_obra', '0004_auto_20180205_1653'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tasahora',
            unique_together={('mes', 'ano', 'colaborador')},
        ),
    ]
