# Generated by Django 2.0.1 on 2018-02-06 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mano_obra', '0010_hojatrabajodiario_creado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='horahojatrabajo',
            name='creado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
