# Generated by Django 2.0.1 on 2018-02-06 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mano_obra', '0012_auto_20180206_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hojatrabajodiario',
            old_name='cantidad_horas',
            new_name='cantidad_minutos',
        ),
    ]
