# Generated by Django 2.0.1 on 2018-02-06 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mano_obra', '0013_auto_20180206_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojatrabajodiario',
            name='tasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mis_dias_trabajados', to='mano_obra.TasaHora'),
        ),
    ]
