# Generated by Django 2.0.1 on 2018-02-06 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mano_obra', '0014_auto_20180206_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horahojatrabajo',
            options={'permissions': [('list_horahojatrabajo', 'Can see list horas trabajos diario')]},
        ),
    ]
