# Generated by Django 2.0.1 on 2018-02-07 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mano_obra', '0015_auto_20180206_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hojatrabajodiario',
            options={'permissions': [('list_hojatrabajodiario', 'Can see list hoja trabajo diario'), ('costos_hojatrabajodiario', 'Can see costos hoja trabajo diario'), ('detail_hojatrabajodiario', 'Can see detail hoja trabajo diario')]},
        ),
    ]
