# Generated by Django 2.0.1 on 2018-02-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mano_obra', '0016_auto_20180207_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='horahojatrabajo',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
