# Generated by Django 2.0.1 on 2018-02-15 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mano_obra', '0017_horahojatrabajo_costo_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hojatrabajodiario',
            options={'permissions': [('list_hojatrabajodiario', 'Can see list hoja trabajo diario'), ('para_otros_hojatrabajodiario', 'Can add hoja trabajo diario para otros'), ('costos_hojatrabajodiario', 'Can see costos hoja trabajo diario'), ('detail_hojatrabajodiario', 'Can see detail hoja trabajo diario')]},
        ),
    ]
