# Generated by Django 2.0.1 on 2018-03-14 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mano_obra', '0018_auto_20180215_1535'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tasahora',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='tasahora',
            name='colaborador',
        ),
        migrations.AlterField(
            model_name='hojatrabajodiario',
            name='tasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mis_dias_trabajados', to='cguno.ColaboradorCostoMesBiable'),
        ),
        migrations.DeleteModel(
            name='TasaHora',
        ),
    ]
