# Generated by Django 2.0.1 on 2018-03-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mano_obra', '0019_auto_20180314_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horahojatrabajo',
            name='costo_total',
        ),
    ]
