# Generated by Django 2.0.1 on 2018-03-15 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mano_obra', '0020_remove_horahojatrabajo_costo_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hojatrabajodiario',
            name='costo_total',
        ),
    ]
