# Generated by Django 2.0.1 on 2018-03-15 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mano_obra', '0021_remove_hojatrabajodiario_costo_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hojatrabajodiario',
            name='cantidad_minutos',
        ),
    ]
