# Generated by Django 2.0.1 on 2018-03-16 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mano_obra', '0022_remove_hojatrabajodiario_cantidad_minutos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horahojatrabajo',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
