# Generated by Django 2.0.4 on 2018-04-24 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0022_auto_20180424_2154'),
        ('cguno', '0057_auto_20180410_1740'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mano_obra', '0026_auto_20180326_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraTrabajoColaboradorLiteralInicial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cantidad_minutos', models.PositiveIntegerField(default=0)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('centro_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cguno.ColaboradorCentroCosto')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_dias_trabajados_iniciales', to='cguno.ColaboradorBiable')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('literal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_horas_trabajadas_iniciales', to='proyectos.Literal')),
            ],
            options={
                'permissions': [['list_horatrabajocolaboradorliteralinicial', 'Puede listar horas colaboradores proyectos iniciales'], ['detail_horatrabajocolaboradorliteralinicial', 'Puede ver detalle hora colaborador proyecto inicial']],
            },
        ),
        migrations.AlterUniqueTogether(
            name='horatrabajocolaboradorliteralinicial',
            unique_together={('colaborador', 'literal')},
        ),
    ]
