# Generated by Django 2.0.4 on 2018-06-19 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mano_obra', '0027_auto_20180424_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hojatrabajodiario',
            options={'permissions': [('list_hojatrabajodiario', 'Can see list hoja trabajo diario'), ('list_hojatrabajodiario_solo_autogestionados', 'Can see list hoja trabajo diario autogestionados'), ('para_otros_hojatrabajodiario', 'Can add hoja trabajo diario para otros'), ('costos_hojatrabajodiario', 'Can see costos hoja trabajo diario'), ('detail_hojatrabajodiario', 'Can see detail hoja trabajo diario')]},
        ),
    ]
