# Generated by Django 2.2 on 2019-06-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mano_obra', '0029_cierrecostosmanoobra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojatrabajodiario',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
