# Generated by Django 2.2 on 2019-06-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mano_obra', '0030_auto_20190612_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojatrabajodiario',
            name='fecha',
            field=models.DateField(),
        ),
    ]
