# Generated by Django 2.2.6 on 2020-08-27 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mano_obra', '0032_distribucionhorahojatrabajo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horahojatrabajo',
            options={'permissions': [('list_horahojatrabajo', 'Can see list horas trabajos diario'), ('verificar_horahojatrabajo', 'Can verificar horas trabajos diario'), ('delete_autogestionadas_otro_horahojatrabajo', 'Can delete horas trabajos diario autogestionadas por otros')]},
        ),
    ]
