# Generated by Django 5.0.14 on 2026-01-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mano_obra', '0034_auto_20200827_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierrecostosmanoobra',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='distribucionhorahojatrabajo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hojatrabajodiario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='horahojatrabajo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='horatrabajocolaboradorliteralinicial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
