# Generated by Django 2.2 on 2019-06-04 20:07

import contabilidad_anticipos.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_anticipos', '0002_auto_20190529_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proformaanticipo',
            old_name='nro_orden_cobro',
            new_name='nro_orden_compra',
        ),
        migrations.AlterField(
            model_name='proformaconfiguracion',
            name='encabezado',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=contabilidad_anticipos.models.ProformaConfiguracion.encabezado_upload_to),
        ),
        migrations.AlterField(
            model_name='proformaconfiguracion',
            name='firma',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=contabilidad_anticipos.models.ProformaConfiguracion.firma_upload_to),
        ),
    ]
