# Generated by Django 2.2 on 2019-06-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_anticipos', '0003_auto_20190604_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformaanticipo',
            name='tipo_documento',
            field=models.CharField(choices=[('PROFORMA', 'Proforma'), ('CUENTA_COBRO', 'Cuenta de Cobro')], max_length=20),
        ),
    ]
