# Generated by Django 2.2 on 2019-06-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_anticipos', '0004_auto_20190605_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformaanticipo',
            name='cobrado',
            field=models.BooleanField(default=False),
        ),
    ]
