# Generated by Django 2.2 on 2019-06-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_anticipos', '0005_proformaanticipo_cobrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformaanticipo',
            name='email_destinatario',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='proformaanticipo',
            name='email_destinatario_dos',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='proformaanticipo',
            name='estado',
            field=models.CharField(choices=[('CREADA', 'Creada'), ('ENVIADA', 'Enviada'), ('ANULADA', 'Anulada'), ('CERRADA', 'Cerrada')], default='CREADA', max_length=20),
        ),
        migrations.AddField(
            model_name='proformaconfiguracion',
            name='email_copia_default',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
