# Generated by Django 2.2 on 2019-06-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_anticipos', '0006_auto_20190606_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformaanticipo',
            name='estado',
            field=models.CharField(choices=[('CREADA', 'Creada'), ('ENVIADA', 'Enviada'), ('EDICION', 'Edicion'), ('ANULADA', 'Anulada'), ('CERRADA', 'Cerrada')], default='CREADA', max_length=20),
        ),
    ]
