# Generated by Django 2.2 on 2019-06-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_anticipos', '0007_auto_20190606_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformaanticipo',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
