# Generated by Django 2.2 on 2019-06-07 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_anticipos', '0003_auto_20190531_1714'),
        ('contabilidad_anticipos', '0008_proformaanticipo_impuesto'),
    ]

    operations = [
    ]
