# Generated by Django 2.2 on 2019-06-17 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_anticipos', '0009_merge_20190607_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proformaanticipo',
            options={'permissions': [('list_proformaanticipo', 'Can list proformas anticipos')]},
        ),
    ]
