# Generated by Django 2.2 on 2019-06-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_anticipos', '0010_auto_20190617_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformaanticipo',
            name='divisa',
            field=models.CharField(choices=[('COP', 'Pesos Colombianos'), ('USD', 'Dólares'), ('EUR', 'Euros')], max_length=10),
        ),
    ]
