# Generated by Django 2.2 on 2019-06-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_anticipos', '0011_auto_20190620_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformaanticipo',
            name='fecha_cambio_estado',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='proformaanticipo',
            name='fecha_segumiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='proformaanticipo',
            name='estado',
            field=models.CharField(choices=[('CREADA', 'Creada'), ('ENVIADA', 'Enviada'), ('RECIBIDA', 'Recibida'), ('EDICION', 'Edicion'), ('ANULADA', 'Anulada'), ('CERRADA', 'Cerrada')], default='CREADA', max_length=20),
        ),
    ]
