# Generated by Django 2.2 on 2019-06-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_anticipos', '0012_auto_20190621_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proformaanticipo',
            old_name='fecha_segumiento',
            new_name='fecha_seguimiento',
        ),
    ]
