# Generated by Django 2.2 on 2019-06-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_anticipos', '0013_auto_20190621_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformaanticipo',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
