# Generated by Django 2.2 on 2019-06-21 21:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_anticipos', '0014_proformaanticipo_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProformaAnticipoEnvios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('archivo', models.FileField(upload_to='')),
                ('version', models.PositiveIntegerField()),
                ('proforma_anticipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios', to='contabilidad_anticipos.ProformaAnticipo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
