# Generated by Django 2.2 on 2019-06-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_anticipos', '0015_proformaanticipoenvios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformaanticipoenvios',
            name='archivo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
