# Generated by Django 2.2 on 2019-07-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_anticipos', '0016_auto_20190621_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformaanticipo',
            name='fecha_cobro',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='proformaanticipoitem',
            name='referencia',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
