# Generated by Django 2.2 on 2019-07-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_anticipos', '0017_auto_20190708_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformaanticipoitem',
            name='referencia',
            field=models.CharField(max_length=120),
        ),
    ]
