# Generated by Django 2.2 on 2019-07-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_anticipos', '0018_auto_20190711_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformaanticipo',
            name='nro_consecutivo',
            field=models.IntegerField(null=True),
        ),
    ]
