# Generated by Django 2.2 on 2019-07-11 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contabilidad_anticipos', '0019_auto_20190711_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformaanticipoenvios',
            name='creado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cobros_enviados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
