# Generated by Django 2.2 on 2019-07-11 17:17

import contabilidad_anticipos.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0050_auto_20190704_1050'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contabilidad_anticipos', '0020_proformaanticipoenvios_creado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformaanticipo',
            name='literales',
            field=models.ManyToManyField(related_name='cobros', to='proyectos.Literal'),
        ),
        migrations.CreateModel(
            name='ProformaAnticipoArchivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('enviar_por_correo', models.BooleanField(default=False)),
                ('nombre_archivo', models.CharField(max_length=300)),
                ('archivo', models.FileField(null=True, upload_to=contabilidad_anticipos.models.ProformaAnticipoArchivo.archivo_upload_to)),
                ('cobro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='contabilidad_anticipos.ProformaAnticipo')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('list_proformaanticipoarchivo', 'Can see list proforma anticipo archivos')],
            },
        ),
    ]
