# Generated by Django 2.2 on 2019-07-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_anticipos', '0022_proformaconfiguracion_email_from_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='proformaanticipo',
            name='observacion',
            field=models.TextField(null=True),
        ),
    ]
