# Generated by Django 2.2 on 2019-07-23 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_anticipos', '0023_proformaanticipo_observacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proformaanticipo',
            options={'permissions': [('list_proformaanticipo', 'Can list proformas anticipos'), ('send_proformaanticipo', 'Can enviar proforma anticipo')]},
        ),
    ]
