# Generated by Django 2.2.6 on 2019-12-04 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_anticipos', '0024_auto_20190723_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proformaconfiguracion',
            name='email_copia_default',
        ),
        migrations.RemoveField(
            model_name='proformaconfiguracion',
            name='email_from_default',
        ),
    ]
