# Generated by Django 2.2.6 on 2020-01-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_anticipos', '0026_proformaanticipo_recibo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proformaanticipo',
            name='tipo_documento',
            field=models.CharField(choices=[('PROFORMA', 'Factura Proforma'), ('CUENTA_COBRO', 'Cuenta de Cobro')], max_length=20),
        ),
    ]
