# Generated by Django 2.0.4 on 2019-04-15 17:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MargenProvedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('margen_deseado', models.DecimalField(decimal_places=3, max_digits=18)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='margenes_por_proveedor', to='items.CategoriaProducto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonedaCambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('cambio', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='ProveedorImportacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('factor_importacion', models.DecimalField(decimal_places=3, default=1, max_digits=18)),
                ('factor_importacion_aereo', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('margenes', models.ManyToManyField(through='importaciones.MargenProvedor', to='items.CategoriaProducto')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provedores_con_moneda', to='importaciones.MonedaCambio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='margenprovedor',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='margenes_por_categoria', to='importaciones.ProveedorImportacion'),
        ),
    ]
