# Generated by Django 2.2.6 on 2020-01-20 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20190515_0755'),
        ('importaciones', '0002_auto_20190416_1051'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='margenprovedor',
            unique_together={('categoria', 'proveedor')},
        ),
    ]
