# Generated by Django 2.2.6 on 2020-02-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0003_auto_20200120_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='margenprovedor',
            name='margen_id_temporal',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='proveedorimportacion',
            name='proveedor_id_temporal',
            field=models.BigIntegerField(null=True),
        ),
    ]
