# Generated by Django 2.2.6 on 2020-03-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0004_auto_20200212_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='monedacambio',
            name='cambio_a_usd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
    ]
