# Generated by Django 2.2.6 on 2020-03-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0005_monedacambio_cambio_a_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monedacambio',
            name='cambio_a_usd',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=18),
        ),
    ]
