# Generated by Django 2.2.6 on 2020-05-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importaciones', '0006_auto_20200318_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='monedacambio',
            name='variacion',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='monedacambio',
            name='variacion_usd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=4),
        ),
    ]
