# Generated by Django 2.0.4 on 2019-05-14 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemventacatalogo',
            options={'permissions': [('list_itemventacatalogo', 'Puede Listar Items Venta Catalogo')]},
        ),
    ]
