# Generated by Django 2.2.6 on 2020-01-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_productos', '0002_auto_20190514_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemventacatalogo',
            name='id_procedencia',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
