# Generated by Django 2.2.6 on 2020-02-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_productos', '0003_itemventacatalogo_id_procedencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemventacatalogo',
            name='item_id_temporal',
            field=models.BigIntegerField(null=True),
        ),
    ]
