# Generated by Django 2.2.6 on 2020-02-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_productos', '0004_itemventacatalogo_item_id_temporal'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemventacatalogo',
            name='unidades_disponibles',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
