# Generated by Django 2.2.6 on 2020-02-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_productos', '0005_itemventacatalogo_unidades_disponibles'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemventacatalogo',
            name='fecha_ultima_entrada',
            field=models.DateField(null=True),
        ),
    ]
