# Generated by Django 2.2.6 on 2020-03-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_productos', '0007_itemventacatalogo_unidad_medida_en_inventario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemventacatalogo',
            name='unidad_medida_catalogo',
        ),
    ]
