# Generated by Django 5.0.14 on 2026-01-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_productos', '0008_remove_itemventacatalogo_unidad_medida_catalogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemventacatalogo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
