# Generated by Django 2.0.4 on 2019-05-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20190416_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaproducto',
            name='nomenclatura',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
