# Generated by Django 2.0.4 on 2018-07-18 22:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cguno', '0060_auto_20180612_1306'),
        ('proyectos', '0040_auto_20180612_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLiteralDiseno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('codigo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('material', models.CharField(max_length=200)),
                ('cantidad_material', models.CharField(blank=True, max_length=200, null=True)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=10)),
                ('proceso', models.CharField(blank=True, max_length=200, null=True)),
                ('acabado', models.CharField(blank=True, max_length=200, null=True)),
                ('prioridad', models.PositiveIntegerField(blank=True, null=True)),
                ('comprar', models.BooleanField(default=False)),
                ('item_cguno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_listado_materiales', to='cguno.ItemsBiable')),
                ('literal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_listado_materiales', to='proyectos.Literal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
