# Generated by Django 2.0.4 on 2018-07-27 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listados_materiales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemliteraldiseno',
            name='cantidad_a_comprar',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='itemliteraldiseno',
            name='cantidad_reservada_inventario',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='itemliteraldiseno',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_listados_materiales_subidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
