# Generated by Django 2.0.4 on 2018-07-27 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listados_materiales', '0003_auto_20180726_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemliteraldiseno',
            old_name='comprar',
            new_name='eliminado',
        ),
        migrations.AddField(
            model_name='itemliteraldiseno',
            name='cambio_cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemliteraldiseno',
            name='registro_anterior',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registro_actual', to='listados_materiales.ItemLiteralDiseno'),
        ),
    ]
