# Generated by Django 2.0.4 on 2018-07-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listados_materiales', '0004_auto_20180727_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemliteraldiseno',
            name='item_cguno_temporal',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
