# Generated by Django 2.0.4 on 2018-07-27 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listados_materiales', '0007_auto_20180727_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemliteraldiseno',
            name='cantidad',
        ),
    ]
