# Generated by Django 2.0.4 on 2018-07-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listados_materiales', '0008_remove_itemliteraldiseno_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantidaditemliteraldiseno',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
