# Generated by Django 2.0.4 on 2018-07-31 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listados_materiales', '0009_auto_20180727_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='cantidaditemliteraldiseno',
            name='cantidad_reservada_inventario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cantidaditemliteraldiseno',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
