# Generated by Django 2.0.4 on 2018-07-31 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listados_materiales', '0010_auto_20180731_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemliteraldiseno',
            name='cantidad_reservada_inventario',
        ),
    ]
