# Generated by Django 2.0.4 on 2018-08-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listados_materiales', '0012_auto_20180731_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemliteraldiseno',
            name='fecha_requerido',
            field=models.DateTimeField(null=True),
        ),
    ]
