# Generated by Django 2.2 on 2019-06-10 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geografia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'permissions': [('list_ciudad', 'Can list ciudad')]},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'permissions': [('list_departamento', 'Can list departamentos')]},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'permissions': [('list_pais', 'Can list paises')]},
        ),
    ]
