# Generated by Django 2.2 on 2019-08-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geografia', '0002_auto_20190610_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='nueva_desde_cotizacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='departamento',
            name='nueva_desde_cotizacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pais',
            name='nueva_desde_cotizacion',
            field=models.BooleanField(default=False),
        ),
    ]
