# Generated by Django 2.0.4 on 2019-03-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_informacion_origen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistemainformacionorigen',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
