# Generated by Django 2.0.4 on 2019-03-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_informacion_origen', '0002_auto_20190328_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistemainformacionorigen',
            name='codigo_amarre',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
