# Generated by Django 2.2 on 2019-06-10 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_informacion_origen', '0003_sistemainformacionorigen_codigo_amarre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sistemainformacionorigen',
            options={'permissions': [('list_sistemainformacionorigen', 'Can list sistemas informacion')]},
        ),
    ]
