# Generated by Django 5.0.14 on 2026-01-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_informacion_origen', '0004_auto_20190610_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistemainformacionorigen',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
