# Generated by Django 2.2 on 2019-08-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones_componentes', '0002_auto_20190809_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacioncomponente',
            name='nro_consecutivo',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
