# Generated by Django 2.2 on 2019-08-10 18:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_productos', '0002_auto_20190514_1314'),
        ('listas_precios', '0002_auto_20190416_1051'),
        ('bandas_eurobelt', '0020_auto_20190806_1610'),
        ('cotizaciones_componentes', '0003_cotizacioncomponente_nro_consecutivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCotizacionComponente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('dias_entrega', models.PositiveIntegerField(default=0)),
                ('descripcion', models.CharField(max_length=120, null=True)),
                ('referencia', models.CharField(max_length=120, null=True)),
                ('unidad_medida', models.CharField(max_length=120, null=True)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=18, null=True)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=18)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('articulo_catalogo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_cotizaciones_componentes', to='catalogo_productos.ItemVentaCatalogo')),
                ('banda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_cotizaciones_componentes', to='bandas_eurobelt.BandaEurobelt')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='cotizaciones_componentes.CotizacionComponente')),
                ('forma_pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_cotizaciones_componentes', to='listas_precios.FormaPagoCanal')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items_cotizaciones_componentes', to='bandas_eurobelt.ComponenteBandaEurobelt')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
