# Generated by Django 2.2 on 2019-08-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones_componentes', '0004_itemcotizacioncomponente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcotizacioncomponente',
            old_name='banda',
            new_name='banda_eurobelt',
        ),
        migrations.RenameField(
            model_name='itemcotizacioncomponente',
            old_name='item',
            new_name='componente_eurobelt',
        ),
        migrations.AlterField(
            model_name='itemcotizacioncomponente',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=18),
            preserve_default=False,
        ),
    ]
