# Generated by Django 2.2 on 2019-08-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones_componentes', '0005_auto_20190813_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcotizacioncomponente',
            name='posicion',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
