# Generated by Django 2.2 on 2019-08-21 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cotizaciones_componentes', '0006_itemcotizacioncomponente_posicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacioncomponente',
            name='creado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_componentes_creadas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotizacioncomponente',
            name='responsable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_componentes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cotizacioncomponente',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_componentes', to='geografia.Ciudad'),
        ),
        migrations.AlterField(
            model_name='cotizacioncomponente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_componentes', to='clientes.ClienteBiable'),
        ),
        migrations.AlterField(
            model_name='cotizacioncomponente',
            name='contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_componentes', to='clientes.ContactoCliente'),
        ),
    ]
