# Generated by Django 2.2 on 2019-08-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones_componentes', '0007_auto_20190821_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacioncomponente',
            name='observaciones',
            field=models.TextField(null=True),
        ),
    ]
