# Generated by Django 2.2 on 2019-08-21 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones_componentes', '0008_cotizacioncomponente_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacioncomponente',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_componentes_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cotizacioncomponente',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_componentes', to=settings.AUTH_USER_MODEL),
        ),
    ]
