# Generated by Django 2.2 on 2019-08-21 16:42

import cotizaciones_componentes.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones_componentes', '0009_auto_20190821_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacioncomponente',
            name='version',
        ),
        migrations.CreateModel(
            name='CotizacionComponenteDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('version', models.PositiveIntegerField()),
                ('pdf_cotizacion', models.FileField(upload_to=cotizaciones_componentes.models.CotizacionComponenteDocumento.archivo_upload_to)),
                ('cotizacion_componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versiones', to='cotizaciones_componentes.CotizacionComponente')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
