# Generated by Django 2.2 on 2019-08-21 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cotizaciones_componentes', '0010_auto_20190821_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacioncomponentedocumento',
            name='creado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_componentes_documentos_creados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
