# Generated by Django 2.2 on 2019-08-26 15:58

import cotizaciones_componentes.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cotizaciones_componentes', '0011_cotizacioncomponentedocumento_creado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacioncomponente',
            name='estado',
            field=models.CharField(choices=[('INI', 'Edición'), ('ENV', 'Enviada'), ('REC', 'Recibida'), ('PRO', 'En Proceso'), ('FIN', 'Entragada Totalmente'), ('ELI', 'Rechazada')], default='INI', max_length=10),
        ),
        migrations.CreateModel(
            name='CotizacionComponenteAdjunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre_imagen', models.CharField(max_length=300)),
                ('adjunto', models.FileField(null=True, upload_to=cotizaciones_componentes.models.CotizacionComponenteAdjunto.archivo_upload_to)),
                ('imagen', imagekit.models.fields.ProcessedImageField(null=True, upload_to=cotizaciones_componentes.models.CotizacionComponenteAdjunto.archivo_upload_to)),
                ('cotizacion_componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imagenes', to='cotizaciones_componentes.CotizacionComponente')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_componentes_imagenes_adjuntadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
