# Generated by Django 2.2 on 2019-08-26 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones_componentes', '0012_auto_20190826_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizacioncomponenteadjunto',
            old_name='nombre_imagen',
            new_name='nombre_adjunto',
        ),
    ]
