# Generated by Django 2.2 on 2019-08-26 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones_componentes', '0013_auto_20190826_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacioncomponenteadjunto',
            name='cotizacion_componente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjuntos', to='cotizaciones_componentes.CotizacionComponente'),
        ),
    ]
