# Generated by Django 2.2 on 2019-08-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones_componentes', '0014_auto_20190826_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacioncomponente',
            name='razon_rechazo',
            field=models.TextField(null=True),
        ),
    ]
