# Generated by Django 2.2.6 on 2020-02-15 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones_componentes', '0018_auto_20200214_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacioncomponente',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='cotizacioncomponente',
            name='razon_rechazo',
        ),
    ]
