# Generated by Django 2.2.6 on 2020-02-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones_componentes', '0019_auto_20200215_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacioncomponente',
            name='observaciones',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cotizacioncomponente',
            name='razon_rechazo',
            field=models.TextField(null=True),
        ),
    ]
