# Generated by Django 2.2.6 on 2020-02-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones_componentes', '0020_auto_20200215_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcotizacioncomponente',
            name='descripcion',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
