# Generated by Django 2.2.6 on 2020-02-16 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones_componentes', '0023_auto_20200216_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacioncomponenteseguimiento',
            name='adjuntos',
        ),
        migrations.RemoveField(
            model_name='cotizacioncomponenteseguimiento',
            name='version_envio',
        ),
    ]
