# Generated by Django 2.2.6 on 2020-02-23 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones_componentes', '0025_cotizacioncomponenteseguimiento_documento_cotizacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcotizacioncomponente',
            options={'permissions': [('list_itemcotizacioncomponente', 'Can list items cotizaciones componentes')]},
        ),
    ]
