# Generated by Django 2.2.6 on 2020-02-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargues_detalles', '0012_remove_itemsliteraldetalle_estado'),
        ('cotizaciones_componentes', '0027_auto_20200225_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacioncomponente',
            name='facturas',
            field=models.ManyToManyField(related_name='cotizaciones_componentes', to='cargues_detalles.FacturaDetalle'),
        ),
    ]
