# Generated by Django 2.2.6 on 2020-03-13 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cotizaciones_componentes', '0028_cotizacioncomponente_facturas'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcotizacioncomponente',
            name='verificada_personalizacion',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='itemcotizacioncomponente',
            name='verificar_personalizacion',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='itemcotizacioncomponente',
            name='verifico_fecha',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='itemcotizacioncomponente',
            name='verifico_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
