# Generated by Django 2.2.6 on 2020-03-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones_componentes', '0029_auto_20200313_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcotizacioncomponente',
            name='verificacion_solicitada',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='itemcotizacioncomponente',
            name='precio_unitario_ori',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=18),
        ),
    ]
