# Generated by Django 2.2.6 on 2020-03-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones_componentes', '0030_auto_20200315_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcotizacioncomponente',
            name='verificacion_solicitada_fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
