# Generated by Django 2.2.6 on 2020-04-16 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones_componentes', '0032_auto_20200315_2044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacioncomponente',
            options={'permissions': [('list_cotizacioncomponente', 'Can list cotizaciones componentes'), ('list_todos_vendedores_cotizacioncomponente', 'Can list cotizaciones componentes otros vendedores')]},
        ),
    ]
