# Generated by Django 2.2.6 on 2020-05-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones_componentes', '0033_auto_20200416_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacioncomponente',
            name='moneda',
            field=models.CharField(default='COP', max_length=3),
        ),
        migrations.AddField(
            model_name='itemcotizacioncomponente',
            name='tasa_cambio_a_dolares',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='itemcotizacioncomponente',
            name='tasa_cambio_a_pesos',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=18),
        ),
    ]
