# Generated by Django 2.2.6 on 2020-05-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones_componentes', '0034_auto_20200505_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcotizacioncomponente',
            name='moneda_origen',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='itemcotizacioncomponente',
            name='moneda_origen_costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
