# Generated by Django 2.2.6 on 2020-05-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones_componentes', '0035_auto_20200505_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcotizacioncomponente',
            name='moneda_origen',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
