# Generated by Django 2.2.6 on 2020-05-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones_componentes', '0037_auto_20200505_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacioncomponente',
            name='fecha_verificacion_cambio_estado',
            field=models.DateField(db_column='fec_ver_cam_est', null=True),
        ),
        migrations.AddField(
            model_name='cotizacioncomponente',
            name='fecha_verificacion_proximo_seguimiento',
            field=models.DateField(db_column='fec_ver_pro_seg', null=True),
        ),
    ]
