# Generated by Django 2.2.6 on 2020-05-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones_componentes', '0039_auto_20200519_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacioncomponenteseguimiento',
            name='estado_anterior',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
