# Generated by Django 2.2.6 on 2020-06-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones_componentes', '0040_cotizacioncomponenteseguimiento_estado_anterior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacioncomponente',
            name='estado',
            field=models.CharField(choices=[('INI', 'Edición'), ('ENV', 'Enviada'), ('REC', 'Recibida'), ('PRO', 'En Proceso'), ('FIN', 'Entragada Totalmente'), ('ELI', 'Rechazada'), ('APL', 'Aplazada')], default='INI', max_length=10),
        ),
    ]
