# Generated by Django 2.2.6 on 2020-06-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones_componentes', '0041_auto_20200601_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacioncomponente',
            name='orden_compra_fecha',
            field=models.DateField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='cotizacioncomponente',
            name='orden_compra_nro',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='cotizacioncomponente',
            name='orden_compra_valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
