# Generated by Django 2.2.6 on 2020-08-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones_componentes', '0042_auto_20200617_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcotizacioncomponente',
            name='cantidad_inicial',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemcotizacioncomponente',
            name='cantidad_venta_perdida',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='itemcotizacioncomponente',
            name='razon_venta_perdida',
            field=models.CharField(choices=[('N.A', 'No Aplica'), ('INVENTARIO', 'Inventario'), ('PRECIO', 'Precio')], max_length=100, null=True),
        ),
    ]
