# Generated by Django 2.2.6 on 2020-08-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones_componentes', '0043_auto_20200801_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcotizacioncomponente',
            name='razon_venta_perdida',
            field=models.CharField(choices=[('N.A', 'No Aplica'), ('INVENTARIO', 'Inventario'), ('PRECIO', 'Precio')], default='N.A', max_length=100),
        ),
    ]
