# Generated by Django 2.2.6 on 2019-12-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorreoAplicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicacion', models.CharField(max_length=300)),
                ('tipo', models.CharField(choices=[('FROM', 'from'), ('BCC', 'bcc'), ('TO', 'to'), ('CC', 'cc')], max_length=5)),
                ('alias_from', models.CharField(max_length=300, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
