# Generated by Django 2.2.6 on 2019-12-03 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correos_servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correoaplicacion',
            options={'permissions': [['list_correoaplicacion', 'Puede listar correos aplicaciones']]},
        ),
    ]
