# Generated by Django 2.0.4 on 2019-05-21 20:03

from django.db import migrations, models
import medios_etiquetas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('alto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ancho', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('color', models.CharField(max_length=10)),
                ('stock_min', models.IntegerField(default=0)),
                ('descripcion', models.CharField(max_length=500)),
                ('imagen', models.FileField(null=True, upload_to=medios_etiquetas.models.Etiqueta.archivo_upload_to)),
            ],
        ),
    ]
