# Generated by Django 2.0.4 on 2019-05-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medios_etiquetas', '0002_auto_20190523_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiqueta',
            name='codigo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
