# Generated by Django 2.0.4 on 2018-04-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteBiable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('en_cguno', models.BooleanField(default=True)),
            ],
        ),
    ]
