# Generated by Django 2.0.4 on 2018-04-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientebiable',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
