# Generated by Django 2.0.4 on 2018-04-27 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20180427_0343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientebiable',
            options={'permissions': [['list_clientebiable', 'Puede listar clientes'], ['detail_clientebiable', 'Puede ver detalle cliente']]},
        ),
    ]
