# Generated by Django 2.0.4 on 2018-06-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20180427_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientebiable',
            name='nit',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
