# Generated by Django 2.0.4 on 2018-06-19 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0006_auto_20180614_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('correo_electronico_2', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=120)),
                ('telefono_2', models.CharField(max_length=120)),
                ('cargo', models.CharField(max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='clientes.ClienteBiable')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contactos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [['list_contactocliente', 'Puede listar contactos clientes']],
            },
        ),
    ]
