# Generated by Django 2.0.4 on 2018-06-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_contactocliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactocliente',
            name='correo_electronico',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactocliente',
            name='correo_electronico_2',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
