# Generated by Django 2.0.4 on 2018-06-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_auto_20180626_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactocliente',
            name='ciudad',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
