# Generated by Django 2.0.4 on 2019-03-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_auto_20180626_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientebiable',
            name='nit',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contactocliente',
            name='cargo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactocliente',
            name='correo_electronico',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactocliente',
            name='correo_electronico_2',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactocliente',
            name='telefono',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='contactocliente',
            name='telefono_2',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
