# Generated by Django 2.2 on 2019-06-11 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_clientebiable_sistema_informacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canaldistribucion',
            options={'permissions': [['list_canaldistribucion', 'Puede listar canales de distribucion']]},
        ),
        migrations.AlterModelOptions(
            name='grupocliente',
            options={'permissions': [['list_grupocliente', 'Puede listar grupos clientes']]},
        ),
        migrations.AlterModelOptions(
            name='tipoindustria',
            options={'permissions': [['list_tipoindustria', 'Puede listar tipos industrias']]},
        ),
    ]
