# Generated by Django 2.2.6 on 2020-02-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_auto_20190809_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientebiable',
            name='nueva_desde_cotizacion',
            field=models.BooleanField(default=True),
        ),
    ]
