# Generated by Django 2.2.6 on 2020-02-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0018_auto_20200207_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientebiable',
            name='sincronizado_sistemas_informacion',
            field=models.BooleanField(default=False),
        ),
    ]
