# Generated by Django 2.2.6 on 2020-02-11 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0019_clientebiable_sincronizado_sistemas_informacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientebiable',
            options={'permissions': [['list_clientebiable', 'Puede listar clientes'], ['detail_clientebiable', 'Puede ver detalle cliente'], ['can_fusionar_clientebiable', 'Puede Fusionar clientes']]},
        ),
    ]
