# Generated by Django 2.2.6 on 2020-02-13 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0003_auto_20200130_1108'),
        ('clientes', '0020_auto_20200211_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientebiable',
            name='colaborador_componentes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes_componentes', to='colaboradores.Colaborador'),
        ),
        migrations.AddField(
            model_name='clientebiable',
            name='colaborador_proyectos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes_proyectos', to='colaboradores.Colaborador'),
        ),
    ]
