# Generated by Django 2.2.6 on 2020-02-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0021_auto_20200213_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactocliente',
            name='id_temporal_crm',
            field=models.BigIntegerField(null=True),
        ),
    ]
