# Generated by Django 2.2.6 on 2020-02-17 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0023_auto_20200214_0010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientebiable',
            options={'permissions': [['list_clientebiable', 'Puede listar clientes'], ['detail_clientebiable', 'Puede ver detalle cliente'], ['can_fusionar_clientebiable', 'Puede Fusionar clientes'], ['can_cambiar_vendedor_componentes_clientebiable', 'Puede Cambiar Vendedor Componentes'], ['can_cambiar_vendedor_proyectos_clientebiable', 'Puede Cambiar Vendedor Proyectos']]},
        ),
    ]
