# Generated by Django 2.2.6 on 2020-02-23 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0025_auto_20200217_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientebiable',
            options={'permissions': [['list_clientebiable', 'Puede listar clientes'], ['detail_clientebiable', 'Puede ver detalle cliente'], ['can_fusionar_clientebiable', 'Puede Fusionar clientes'], ['can_consultar_historico_precios_clientebiable', 'Puede Consultar Historico Precios'], ['can_cambiar_vendedor_componentes_clientebiable', 'Puede Cambiar Vendedor Componentes'], ['can_cambiar_vendedor_proyectos_clientebiable', 'Puede Cambiar Vendedor Proyectos']]},
        ),
    ]
