# Generated by Django 2.2.6 on 2020-02-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0026_auto_20200223_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientebiable',
            name='nit',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
    ]
