# Generated by Django 2.2.6 on 2020-02-26 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0027_auto_20200225_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactocliente',
            options={'permissions': [['list_contactocliente', 'Puede listar contactos clientes'], ['can_fusionar_contactocliente', 'Puede Fusionar contactos clientes']]},
        ),
    ]
