# Generated by Django 2.0.4 on 2018-05-07 16:11

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nro_cotizacion', models.PositiveIntegerField(blank=True, null=True)),
                ('unidad_negocio', models.CharField(max_length=10)),
                ('cliente', models.CharField(max_length=200)),
                ('descripcion_cotizacion', models.CharField(max_length=500)),
                ('contacto', models.CharField(max_length=400)),
                ('estado', models.CharField(max_length=200)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('valor_ofertado', models.DecimalField(decimal_places=2, max_digits=20)),
                ('valor_orden_compra', models.DecimalField(decimal_places=2, max_digits=20)),
                ('costo_presupuestado', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'permissions': [['list_cotizacion', 'Puede listar cotizaciones']],
            },
        ),
    ]
