# Generated by Django 2.0.4 on 2018-05-07 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_seguimientocotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientocotizacion',
            name='cotizacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mis_seguimientos', to='cotizaciones.Cotizacion'),
            preserve_default=False,
        ),
    ]
