# Generated by Django 2.0.4 on 2018-05-07 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0004_seguimientocotizacion_cotizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimientocotizacion',
            name='estado',
        ),
    ]
