# Generated by Django 2.0.4 on 2018-05-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0005_remove_seguimientocotizacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientocotizacion',
            name='estado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
