# Generated by Django 2.0.4 on 2018-05-10 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0008_cotizacion_responsable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'permissions': [['list_cotizacion', 'Puede listar cotizaciones'], ['detail_cotizacion', 'Puede ver detalle cotizacion'], ['gestionar_cotizacion', 'Puede gestionar cotizacion']]},
        ),
    ]
