# Generated by Django 2.0.4 on 2018-05-11 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0009_auto_20180510_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'permissions': [['list_cotizacion', 'Puede listar cotizaciones'], ['detail_cotizacion', 'Puede ver detalle cotizacion'], ['gestionar_cotizacion', 'Puede gestionar cotizacion'], ['list_all_cotizacion', 'Puede listar todas las cotizaciones']]},
        ),
    ]
