# Generated by Django 2.0.4 on 2018-05-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0011_auto_20180511_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
