# Generated by Django 2.0.4 on 2018-05-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0012_auto_20180511_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='abrir_carpeta',
            field=models.BooleanField(default=False),
        ),
    ]
