# Generated by Django 2.0.4 on 2018-05-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0013_cotizacion_abrir_carpeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='nro_cotizacion',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
