# Generated by Django 2.0.4 on 2018-05-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0014_auto_20180515_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='orden_compra_nro',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
