# Generated by Django 2.0.4 on 2018-05-31 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0016_auto_20180530_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='crear_literal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='crear_literal_id_proyecto',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
