# Generated by Django 2.0.4 on 2018-06-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0017_auto_20180531_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_entrega_pactada_cotizacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
