# Generated by Django 2.0.4 on 2018-06-07 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0018_cotizacion_fecha_entrega_pactada_cotizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='cliente',
        ),
    ]
