# Generated by Django 2.0.4 on 2018-06-07 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20180427_0509'),
        ('cotizaciones', '0019_remove_cotizacion_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.ClienteBiable'),
        ),
    ]
