# Generated by Django 2.0.4 on 2018-06-14 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cotizaciones', '0020_cotizacion_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
