# Generated by Django 2.0.4 on 2018-06-21 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_auto_20180619_1909'),
        ('cotizaciones', '0021_cotizacion_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='contacto_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mis_contizaciones', to='clientes.ContactoCliente'),
        ),
    ]
