# Generated by Django 2.0.4 on 2018-06-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0022_cotizacion_contacto_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='contacto',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
