# Generated by Django 2.0.4 on 2018-08-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0023_auto_20180622_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='dias_espera_cambio_estado',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='estado_observacion_adicional',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_cambio_estado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='origen_cotizacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
