# Generated by Django 2.0.4 on 2018-08-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0025_auto_20180822_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='estado_observacion_adicional',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
