# Generated by Django 2.0.4 on 2019-01-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0029_auto_20180918_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_cambio_estado_cerrado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
