# Generated by Django 2.0.4 on 2019-01-21 17:39

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0030_cotizacion_fecha_cambio_estado_cerrado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoCotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre_archivo', models.CharField(max_length=300)),
                ('archivo', models.FileField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
