# Generated by Django 2.0.4 on 2019-01-21 19:49

import cotizaciones.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0031_archivocotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivocotizacion',
            name='cotizacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='mis_documentos', to='cotizaciones.Cotizacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archivocotizacion',
            name='archivo',
            field=models.FileField(null=True, upload_to=cotizaciones.models.ArchivoCotizacion.archivo_upload_to),
        ),
    ]
