# Generated by Django 2.0.4 on 2019-01-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0035_auto_20190123_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='orden_compra_nro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
