# Generated by Django 2.2 on 2019-06-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0036_auto_20190129_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='costo_presupuestado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='valor_ofertado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='valor_orden_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
