# Generated by Django 2.2 on 2019-09-23 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0037_auto_20190626_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='crear_literal',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='crear_literal_id_proyecto',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='cotizacion_inicial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cotizaciones.Cotizacion'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.ClienteBiable'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='contacto',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='contacto_cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mis_contizaciones', to='clientes.ContactoCliente'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado_observacion_adicional',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_cambio_estado',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_cambio_estado_cerrado',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_entrega_pactada',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_entrega_pactada_cotizacion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_limite_segumiento_estado',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='nro_cotizacion',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='observacion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='orden_compra_fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='orden_compra_nro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='origen_cotizacion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
