# Generated by Django 2.2 on 2019-09-23 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0038_auto_20190923_0830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizacion',
            old_name='abrir_carpeta',
            new_name='relacionada',
        ),
    ]
