# Generated by Django 2.2 on 2019-09-24 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0039_auto_20190923_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='cotizacion_inicial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_adicionales', to='cotizaciones.Cotizacion'),
        ),
    ]
