# Generated by Django 2.2 on 2019-10-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0040_auto_20190924_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='revisada',
            field=models.BooleanField(default=False),
        ),
    ]
