# Generated by Django 2.2.6 on 2019-11-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0044_auto_20191105_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='dias_pactados_entrega_proyecto',
            field=models.IntegerField(null=True),
        ),
    ]
