# Generated by Django 2.2.6 on 2019-11-18 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0045_cotizacion_dias_pactados_entrega_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionInicioProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=400)),
                ('require_documento', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CondicionInicioProyectoCotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField(null=True)),
                ('documento', models.FileField(null=True, upload_to='')),
                ('condicion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cotizaciones.CondicionInicioProyecto')),
                ('cotizacion_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condiciones_inicio', to='cotizaciones.Cotizacion')),
            ],
        ),
    ]
