# Generated by Django 2.2.6 on 2019-11-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0047_auto_20191118_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condicioninicioproyectocotizacion',
            name='condicion',
        ),
        migrations.AddField(
            model_name='condicioninicioproyectocotizacion',
            name='descripcion',
            field=models.CharField(default='exit', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='condicioninicioproyectocotizacion',
            name='documento_nombre',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='condicioninicioproyectocotizacion',
            name='require_documento',
            field=models.BooleanField(default=False),
        ),
    ]
