# Generated by Django 2.2.6 on 2019-11-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0048_auto_20191118_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='esperando_condiciones_inicio',
            field=models.BooleanField(default=True),
        ),
    ]
