# Generated by Django 2.2.6 on 2019-11-20 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0049_cotizacion_esperando_condiciones_inicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizacion',
            old_name='esperando_condiciones_inicio',
            new_name='listo_para_iniciar',
        ),
    ]
