# Generated by Django 2.2.6 on 2019-11-20 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0050_auto_20191120_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='listo_para_iniciar',
        ),
    ]
