# Generated by Django 2.2.6 on 2019-11-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0053_auto_20191120_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicioninicioproyectocotizacion',
            name='documento_nombre',
            field=models.CharField(default='hola', max_length=120),
            preserve_default=False,
        ),
    ]
