# Generated by Django 2.2.6 on 2019-11-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0054_auto_20191122_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicioninicioproyectocotizacion',
            name='documento_nombre',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
