# Generated by Django 2.2.6 on 2019-11-23 01:29

import cotizaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0055_auto_20191122_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicioninicioproyectocotizacion',
            name='documento',
            field=models.FileField(null=True, upload_to=cotizaciones.models.CondicionInicioProyectoCotizacion.archivo_upload_to),
        ),
        migrations.AlterField(
            model_name='condicioninicioproyectocotizacion',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
