# Generated by Django 2.2.6 on 2019-11-25 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0056_auto_20191122_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condicioninicioproyectocotizacion',
            name='documento_nombre',
        ),
    ]
