# Generated by Django 2.2.6 on 2019-11-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0058_auto_20191125_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='fecha_entrega_pactada',
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
