# Generated by Django 2.2.6 on 2019-11-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0059_auto_20191128_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'permissions': [['list_cotizaciones_abrir_carpeta', 'Puede listar cotizaciones para abrir carpeta'], ['list_cotizaciones_notificaciones_consecutivo_proyectos', 'Puede listar cotizaciones para notificaciones consecutivo proyectos'], ['eliminar_cotizacion_notificacion_consecutivo_proyectos', 'Puede eliminar notificacion cotizaciones en consecutivo proyectos'], ['rel_cotizacion_adicional_a_literal', 'Puede relacionar cotizacion adicional a literal'], ['rel_cotizacion_proyecto', 'Puede relacionar cotizacion a proyecto'], ['list_cotizacion', 'Puede listar cotizaciones'], ['detail_cotizacion', 'Puede ver detalle cotizacion'], ['gestionar_cotizacion', 'Puede gestionar cotizacion'], ['list_all_cotizacion', 'Puede listar todas las cotizaciones'], ['list_all_cotizaciones_activas', 'Puede listar todas las cotizaciones activas'], ['list_tuberia_ventas', 'Puede ver la tuberia de bentas'], ['list_tuberia_informe_uno', 'Puede Ver informe de tuberia de ventas'], ['change_cerrada', 'Puede Editar Cotizacion Cerrada']]},
        ),
    ]
