# Generated by Django 2.2.6 on 2019-11-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0060_auto_20191129_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='condicioninicioproyecto',
            name='condicion_especial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='condicioninicioproyectocotizacion',
            name='condicion_especial',
            field=models.BooleanField(default=False),
        ),
    ]
