# Generated by Django 2.2.6 on 2019-12-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0061_auto_20191129_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='origen_cotizacion',
            field=models.CharField(default='hola', max_length=100),
            preserve_default=False,
        ),
    ]
