# Generated by Django 2.2.6 on 2019-12-02 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0062_auto_20191201_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='contacto',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='contacto_cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='mis_contizaciones', to='clientes.ContactoCliente'),
            preserve_default=False,
        ),
    ]
