# Generated by Django 2.2.6 on 2019-12-02 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0063_auto_20191202_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='contacto',
        ),
    ]
