# Generated by Django 2.2.6 on 2019-12-17 03:18

import cotizaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0064_remove_cotizacion_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='orden_compra_archivo',
            field=models.FileField(null=True),
        ),
    ]
