# Generated by Django 2.2.6 on 2020-02-11 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0066_auto_20191218_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_proyectos', to='clientes.ClienteBiable'),
        ),
    ]
