# Generated by Django 2.2.6 on 2020-06-11 14:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0069_cotizacionordencompra'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionOrdenCompraPlanPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fecha', models.DateField()),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_pagos', to='cotizaciones.CotizacionOrdenCompra')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
