# Generated by Django 2.2.6 on 2020-07-29 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0070_cotizacionordencompraplanpago'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CotizacionOrdenCompraPlanPago',
        ),
    ]
