# Generated by Django 2.2.6 on 2020-07-29 17:27

import cotizaciones.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0071_delete_cotizacionordencompraplanpago'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionPagoProyectado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('valor_orden_compra', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('orden_compra_nro', models.CharField(max_length=100, null=True)),
                ('orden_compra_fecha', models.DateField(null=True)),
                ('orden_compra_archivo', models.FileField(null=True, upload_to=cotizaciones.models.CotizacionPagoProyectado.archivo_upload_to)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_proyectados', to='cotizaciones.Cotizacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CotizacionPagoProyectadoAcuerdoPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fecha', models.DateField()),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acuerdos_pagos', to='cotizaciones.CotizacionPagoProyectado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CotizacionOrdenCompra',
        ),
    ]
