# Generated by Django 2.2.6 on 2020-07-29 17:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0072_auto_20200729_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizacionpagoproyectadoacuerdopago',
            old_name='fecha',
            new_name='fecha_proyectada',
        ),
        migrations.RenameField(
            model_name='cotizacionpagoproyectadoacuerdopago',
            old_name='valor',
            new_name='valor_proyectado',
        ),
        migrations.AddField(
            model_name='cotizacionpagoproyectadoacuerdopago',
            name='fecha_real',
            field=models.DateField(default=datetime.datetime(2020, 7, 29, 17, 30, 22, 718908, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotizacionpagoproyectadoacuerdopago',
            name='valor_real',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
