# Generated by Django 2.2.6 on 2020-07-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0076_cotizacionpagoproyectadoacuerdopago_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacionpagoproyectadoacuerdopago',
            name='fecha_proyectada',
            field=models.DateField(null=True),
        ),
    ]
