# Generated by Django 2.2.6 on 2020-07-31 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0077_auto_20200729_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacionpagoproyectado',
            name='notificada_por_correo',
            field=models.BooleanField(default=False),
        ),
    ]
