# Generated by Django 2.2.6 on 2020-07-31 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0078_cotizacionpagoproyectado_notificada_por_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacionpagoproyectadoacuerdopagopago',
            name='notificada_por_correo',
            field=models.BooleanField(default=False),
        ),
    ]
