# Generated by Django 2.2.6 on 2020-08-04 16:40

import cotizaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0080_auto_20200731_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='cotizacion_archivo',
            field=models.FileField(null=True, upload_to=cotizaciones.models.Cotizacion.archivo_cotizacion_upload_to),
        ),
    ]
