# Generated by Django 2.2.6 on 2020-08-14 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0083_cotizacionpagoproyectadoacuerdopago_creado_por'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacionpagoproyectadoacuerdopago',
            options={'permissions': [('change_fecha_proyectada_cotizacionpagoproyectadoacuerdopago', 'Can change fecha proyectada acuerdo pago')]},
        ),
    ]
