# Generated by Django 2.2.6 on 2020-08-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0084_auto_20200814_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivocotizacion',
            name='tipo',
            field=models.CharField(choices=[('OTROS', 'Otros'), ('COTIZACION', 'Cotización'), ('ORDENCOMPRA', 'Orden de Compra'), ('CONTRATO', 'Contrato'), ('POLIZA', 'Póliza')], default='OTROS', max_length=20),
        ),
    ]
