# Generated by Django 2.2.6 on 2020-08-14 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0085_archivocotizacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivocotizacion',
            name='orden_compra',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orden_compra_documento', to='cotizaciones.CotizacionPagoProyectado'),
        ),
    ]
