# Generated by Django 2.2.6 on 2020-08-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0087_auto_20200814_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacionpagoproyectado',
            name='orden_compra_archivo',
        ),
    ]
