# Generated by Django 2.2.6 on 2020-08-15 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0088_remove_cotizacionpagoproyectado_orden_compra_archivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivocotizacion',
            options={'permissions': [('list_archivocotizacion', 'Can see list archivos cotizaciones'), ('delete_tipo_cotizacion_archivocotizacion', 'Can delete archivos cotizaciones tipo cotización')]},
        ),
    ]
