# Generated by Django 2.2.6 on 2020-09-03 16:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0065_auto_20200226_0645'),
        ('proyectos_equipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipoproyecto',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='equipoproyecto',
            name='fecha_fabricacion',
            field=models.DateField(db_column='fec_fabri', null=True),
        ),
        migrations.AddField(
            model_name='equipoproyecto',
            name='identificador',
            field=models.PositiveIntegerField(db_column='ident', default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipoproyecto',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='equipoproyecto',
            name='nro_consecutivo',
            field=models.PositiveIntegerField(db_column='nro_conse', default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipoequipo',
            name='sigla',
            field=models.CharField(default='f', max_length=2, unique=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='equipoproyecto',
            unique_together={('literal', 'nro_consecutivo')},
        ),
        migrations.CreateModel(
            name='TipoEquipoCampoEquipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamano', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=120)),
                ('valor', models.CharField(max_length=200)),
                ('unidad_medida', models.CharField(db_column='um', max_length=100)),
                ('opciones_list', models.TextField(db_column='lst_opt', null=True)),
                ('equipo', models.ForeignKey(db_column='equ', on_delete=django.db.models.deletion.PROTECT, related_name='campos_valores', to='proyectos_equipos.EquipoProyecto')),
            ],
            options={
                'db_table': 'equip_proy_campos',
                'permissions': [('list_tipoequipocampoequipo', 'Can list equipo poryecto campos')],
            },
        ),
        migrations.CreateModel(
            name='TipoEquipoCampo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('tamano', models.PositiveIntegerField(default=100)),
                ('tamano_columna', models.PositiveIntegerField(default=12)),
                ('unidad_medida', models.CharField(db_column='um', max_length=100)),
                ('tipo', models.CharField(choices=[('NUMBER', 'Número'), ('TEXT', 'Texto'), ('LIST', 'Lista')], db_column='tip', default='TEXT', max_length=20)),
                ('opciones_list', models.TextField(db_column='lst_opt', null=True)),
                ('tipo_equipo', models.ForeignKey(db_column='tip_equ', on_delete=django.db.models.deletion.PROTECT, related_name='campos', to='proyectos_equipos.TipoEquipo')),
            ],
            options={
                'db_table': 'tip_equip_campos',
                'permissions': [('list_tipoequipocampo', 'Can list campos tipo equipo')],
            },
        ),
        migrations.RemoveField(
            model_name='equipoproyecto',
            name='nro_identificacion',
        ),
        migrations.CreateModel(
            name='TipoEquipoClase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('sigla', models.CharField(max_length=2, unique=True)),
                ('tipo_equipo', models.ForeignKey(db_column='tip_equ', on_delete=django.db.models.deletion.PROTECT, related_name='clases_tipo_equipo', to='proyectos_equipos.TipoEquipo')),
            ],
            options={
                'db_table': 'tip_equip_clase',
                'permissions': [('list_tipoequipoclase', 'Can list clases tipo equipo')],
                'unique_together': {('sigla', 'tipo_equipo')},
            },
        ),
    ]
