# Generated by Django 2.2.6 on 2020-09-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_equipos', '0002_auto_20200903_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoequipoclase',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
