# Generated by Django 2.2.6 on 2020-09-03 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_equipos', '0003_tipoequipoclase_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipoproyecto',
            name='tipo_equipo',
        ),
        migrations.AddField(
            model_name='equipoproyecto',
            name='tipo_equipo_clase',
            field=models.ForeignKey(db_column='tip_equ_cla', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='proyectos_equipos.TipoEquipoClase'),
            preserve_default=False,
        ),
    ]
