# Generated by Django 2.2.6 on 2020-09-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_equipos', '0004_auto_20200903_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoequipocampo',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tipoequipocampo',
            name='unidad_medida',
            field=models.CharField(db_column='um', max_length=100, null=True),
        ),
    ]
