# Generated by Django 2.2.6 on 2020-09-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_equipos', '0005_auto_20200903_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipoproyecto',
            name='identificador',
            field=models.CharField(db_column='ident', max_length=100, unique=True),
        ),
    ]
