# Generated by Django 2.2.6 on 2020-09-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_equipos', '0007_auto_20200904_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoequipocampoequipo',
            name='tamano_columna',
            field=models.PositiveIntegerField(default=12),
        ),
    ]
