# Generated by Django 2.2.6 on 2020-09-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_equipos', '0008_auto_20200904_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoequipocampoequipo',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
