# Generated by Django 2.2.6 on 2020-09-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_equipos', '0009_tipoequipocampoequipo_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoequipocampo',
            name='obligatorio',
            field=models.BooleanField(default=True),
        ),
    ]
