# Generated by Django 2.2.6 on 2020-09-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_equipos', '0012_auto_20200905_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoequipoclase',
            name='sigla',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
