# Generated by Django 2.0.2 on 2018-02-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AditionalDefaultPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('list_user', 'Can list user'), ('list_permission', 'Can list permission'), ('detail_user', 'Can see user')),
                'managed': False,
            },
        ),
    ]
