# Generated by Django 2.2 on 2019-07-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0005_auto_20180217_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuAdminPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('menu_admin_permisos', 'Menu Admin Permisos'), ('menu_admin_permisos_grupos', 'Menu Admin Grupos Permisos'), ('menu_admin_terceros_usuarios', 'Menu Admin Terceros Usuarios'), ('menu_admin_terceros_colaboradores', 'Menu Admin Terceros Colaboradores'), ('menu_admin_terceros_proveedores', 'Menu Admin Terceros Proveedores')),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModuloPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('modulo_admin', 'Modulo Admin'), ('modulo_proyectos', 'Modulo Proyectos'), ('modulo_ventas', 'Modulo Ventas'), ('modulo_medios', 'Modulo Medios'), ('modulo_sistemas', 'Modulo Sistemas'), ('modulo_contabilidad', 'Modulo Contabilidad')),
                'managed': False,
            },
        ),
    ]
