# Generated by Django 2.2 on 2019-07-22 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0006_menuadminpermission_modulopermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuadminpermission',
            options={'managed': False, 'permissions': (('menu_admin_permisos', 'Menu Admin Permisos'), ('menu_admin_permisos_grupos', 'Menu Admin Grupos Permisos'), ('menu_admin_terceros_usuarios', 'Menu Admin Terceros Usuarios'), ('menu_admin_terceros_clientes', 'Menu Admin Terceros Clientes'), ('menu_admin_terceros_costos_nomina', 'Menu Admin Terceros Costos Nomina'), ('menu_admin_terceros_colaboradores', 'Menu Admin Terceros Colaboradores'), ('menu_admin_terceros_proveedores', 'Menu Admin Terceros Proveedores'))},
        ),
    ]
