# Generated by Django 2.2 on 2019-08-08 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0007_auto_20190722_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulopermission',
            options={'managed': False, 'permissions': (('modulo_admin', 'Modulo Admin'), ('modulo_proyectos', 'Modulo Proyectos'), ('modulo_ventas', 'Modulo Ventas'), ('modulo_ventas_componentes', 'Modulo Ventas Componentes'), ('modulo_medios', 'Modulo Medios'), ('modulo_sistemas', 'Modulo Sistemas'), ('modulo_contabilidad', 'Modulo Contabilidad'))},
        ),
    ]
