# Generated by Django 2.2.6 on 2019-12-09 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0009_menuproyectospermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuproyectospermission',
            options={'managed': False, 'permissions': (('menu_proyectos_proyectos', 'Menu Proyectos Proyectos'), ('menu_proyectos_fases', 'Menu Proyectos Fases'))},
        ),
    ]
