# Generated by Django 2.2.6 on 2019-12-09 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0010_auto_20191209_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuproyectospermission',
            options={'managed': False, 'permissions': (('menu_proyectos_proyectos', 'Menu Proyectos Proyectos'), ('menu_proyectos_fases', 'Menu Proyectos Fases'), ('menu_proyectos_mano_obra_verificar_horas', 'Menu Proyectos Mano Obra Verificar Horas'), ('menu_proyectos_mano_obra_hojas_trabajo', 'Menu Proyectos Mano Obra Hojas de Trabajo'), ('menu_proyectos_mano_obra_horas_hojas_trabajo', 'Menu Proyectos Mano Obra Horas Hojas de Trabajo'))},
        ),
    ]
