# Generated by Django 2.2.6 on 2019-12-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0011_auto_20191209_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuVentasProyectosPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('menu_ventas_proyectos_configuraciones', 'Menu Ventas Proyectos Configuraciones'), ('menu_ventas_proyectos_resumen_tuberia_ventas', 'Menu Ventas Proyectos Resumen Tuberia Ventas'), ('menu_ventas_proyectos_cotizaciones', 'Menu Ventas Proyectos Cotizaciones'), ('menu_ventas_proyectos_clientes', 'Menu Ventas Proyectos Clientes')),
                'managed': False,
            },
        ),
    ]
