# Generated by Django 2.2.6 on 2019-12-09 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0013_auto_20191209_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuadminpermission',
            options={'managed': False, 'permissions': (('menu_admin_permisos', 'Menu Admin Permisos'), ('menu_admin_permisos_grupos', 'Menu Admin Grupos Permisos'), ('menu_admin_terceros_usuarios', 'Menu Admin Terceros Usuarios'), ('menu_admin_terceros_clientes', 'Menu Admin Terceros Clientes'), ('menu_admin_terceros_costos_nomina', 'Menu Admin Terceros Costos Nomina'), ('menu_admin_terceros_colaboradores', 'Menu Admin Terceros Colaboradores'), ('menu_admin_terceros_proveedores', 'Menu Admin Terceros Proveedores'), ('menu_admin_sistemas_informacion', 'Menu Admin Sistemas Información'), ('menu_admin_importaciones', 'Menu Admin Importaciones'), ('menu_admin_geografia', 'Menu Admin Geografía'), ('menu_admin_items', 'Menu Admin Items'), ('menu_admin_listas_precios', 'Menu Admin Listas Precios'))},
        ),
    ]
