# Generated by Django 2.2.6 on 2020-02-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0014_auto_20191209_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuVentasComponentesPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('menu_ventas_componentes_cotizaciones', 'Menu Ventas Componentes Cotizaciones'), ('menu_ventas_componentes_clientes', 'Menu Ventas Componentes Clientes')),
                'managed': False,
            },
        ),
    ]
