# Generated by Django 2.2.6 on 2020-02-18 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0015_menuventascomponentespermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulopermission',
            options={'managed': False, 'permissions': (('modulo_admin', 'Modulo Admin'), ('modulo_proyectos', 'Modulo Proyectos'), ('modulo_ventas', 'Modulo Ventas'), ('modulo_ventas_componentes', 'Modulo Ventas Componentes'), ('modulo_medios', 'Modulo Medios'), ('modulo_sistemas', 'Modulo Sistemas'), ('modulo_contabilidad', 'Modulo Contabilidad'), ('modulo_bandas_eurobelt', 'Modulo Eurobelt'))},
        ),
    ]
