# Generated by Django 2.2.6 on 2020-04-15 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0019_auto_20200225_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aditionaldefaultpermission',
            options={'managed': False, 'permissions': (('list_user', 'Can list user'), ('can_change_user_password', 'Puede cambiar password de usuario'), ('list_permission', 'Can list permission'), ('list_group', 'Can list group'), ('detail_user', 'Can detail user'), ('detail_group', 'Can detail grupo'), ('make_user_superuser', 'Can make user superuser'), ('make_user_staff', 'Can make user staff'), ('make_user_active', 'Can make user active'))},
        ),
    ]
