# Generated by Django 2.2.6 on 2020-08-01 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0022_auto_20200617_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuventascomponentespermission',
            options={'managed': False, 'permissions': (('menu_ventas_componentes_cotizaciones', 'Menu Ventas Componentes Cotizaciones'), ('menu_ventas_componentes_clientes', 'Menu Ventas Componentes Clientes'), ('menu_ventas_componentes_informe_ventas_perdidas', 'Menu Ventas Componentes Informe Ventas Perdidas'))},
        ),
    ]
