# Generated by Django 2.2.6 on 2020-08-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0022_auto_20200617_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuGerenciaPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('menu_gerencia_informe_ventas', 'Menu Gerencia Informe Ventas'), ('menu_gerencia_informe_acuerdo_pagos_valores', 'Menu Gerencia Acuerdos de Pagos Valores')),
                'managed': False,
            },
        ),
    ]
