# Generated by Django 2.2.6 on 2020-08-27 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0024_auto_20200826_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulopermission',
            options={'managed': False, 'permissions': (('modulo_admin', 'Modulo Admin'), ('modulo_proyectos', 'Modulo Proyectos'), ('modulo_ventas', 'Modulo Ventas'), ('modulo_ventas_componentes', 'Modulo Ventas Componentes'), ('modulo_medios', 'Modulo Medios'), ('modulo_sistemas', 'Modulo Sistemas'), ('modulo_contabilidad', 'Modulo Contabilidad'), ('modulo_bandas_eurobelt', 'Modulo Eurobelt'), ('modulo_gerencia', 'Modulo Gerencia'), ('modulo_postventa', 'Modulo PostVenta'))},
        ),
    ]
