# Generated by Django 2.2 on 2019-08-16 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cotizaciones_componentes', '0006_itemcotizacioncomponente_posicion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionComponenteEnvio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('correo_from', models.CharField(max_length=500)),
                ('correos_to', models.CharField(max_length=500)),
                ('archivo', models.FileField(null=True, upload_to='')),
                ('version', models.PositiveIntegerField()),
                ('cotizacion_componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios_emails', to='cotizaciones_componentes.CotizacionComponente')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_componentes_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
