# Generated by Django 2.2 on 2019-08-16 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad_anticipos', '0024_auto_20190723_0859'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('envios_emails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CobroEnvio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('correo_from', models.CharField(max_length=500)),
                ('correos_to', models.CharField(max_length=500)),
                ('archivo', models.FileField(null=True, upload_to='')),
                ('version', models.PositiveIntegerField()),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros_enviadas', to=settings.AUTH_USER_MODEL)),
                ('proforma_anticipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios_cobros', to='contabilidad_anticipos.ProformaAnticipo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
