# Generated by Django 2.2.6 on 2020-02-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones_componentes', '0024_auto_20200216_1227'),
        ('envios_emails', '0003_auto_20190821_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacioncomponenteenvio',
            name='adjuntos',
            field=models.ManyToManyField(to='cotizaciones_componentes.CotizacionComponenteAdjunto'),
        ),
    ]
