# Generated by Django 2.2.6 on 2020-02-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envios_emails', '0004_cotizacioncomponenteenvio_adjuntos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacioncomponenteenvio',
            name='adjuntos',
        ),
    ]
