# Generated by Django 2.2.6 on 2020-09-09 14:14

from django.db import migrations, models
import django.db.models.deletion
import documentaciones_procesos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentacionArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('lider', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'doct_area',
            },
        ),
        migrations.CreateModel(
            name='DocumentacionProceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'doct_proc',
            },
        ),
        migrations.CreateModel(
            name='DocumentacionProcesoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(db_column='nombre', max_length=120)),
                ('descripcion', models.TextField(db_column='desc')),
                ('documento', models.FileField(db_column='file', upload_to=documentaciones_procesos.models.documento_proceso_upload_to)),
            ],
            options={
                'db_table': 'doct_proc_docts',
            },
        ),
        migrations.CreateModel(
            name='DocumentacionProcesoResponsable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('extencion', models.PositiveIntegerField(db_column='ext', null=True)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsables', to='documentaciones_procesos.DocumentacionProceso')),
            ],
            options={
                'db_table': 'doct_proc_resp',
            },
        ),
    ]
